// Code generated by avx512test. DO NOT EDIT.

#include "../../../../../../runtime/textflag.h"

TEXT asmtest_avx512_vpopcntdq(SB), NOSPLIT, $0
	//TODO: VPOPCNTD X22, K2, X28                              // 62227d0a55e6
	//TODO: VPOPCNTD (R14), K2, X28                            // 62427d0a5526
	//TODO: VPOPCNTD -7(DI)(R8*8), K2, X28                     // 62227d0a55a4c7f9ffffff
	//TODO: VPOPCNTD Y24, K5, Y11                              // 62127d2d55d8
	//TODO: VPOPCNTD -15(R14)(R15*1), K5, Y11                  // 62127d2d559c3ef1ffffff
	//TODO: VPOPCNTD -15(BX), K5, Y11                          // 62727d2d559bf1ffffff
	//TODO: VPOPCNTD Z2, K3, Z22                               // 62e27d4b55f2
	//TODO: VPOPCNTD Z31, K3, Z22                              // 62827d4b55f7
	//TODO: VPOPCNTD 7(SI)(DI*4), K3, Z22                      // 62e27d4b55b4be07000000
	//TODO: VPOPCNTD -7(DI)(R8*2), K3, Z22                     // 62a27d4b55b447f9ffffff
	//TODO: VPOPCNTD Z2, K3, Z7                                // 62f27d4b55fa
	//TODO: VPOPCNTD Z31, K3, Z7                               // 62927d4b55ff
	//TODO: VPOPCNTD 7(SI)(DI*4), K3, Z7                       // 62f27d4b55bcbe07000000
	//TODO: VPOPCNTD -7(DI)(R8*2), K3, Z7                      // 62b27d4b55bc47f9ffffff
	//TODO: VPOPCNTQ X19, K4, X7                               // 62b2fd0c55fb
	//TODO: VPOPCNTQ 99(R15)(R15*4), K4, X7                    // 6292fd0c55bcbf63000000
	//TODO: VPOPCNTQ 15(DX), K4, X7                            // 62f2fd0c55ba0f000000
	//TODO: VPOPCNTQ Y5, K2, Y1                                // 62f2fd2a55cd
	//TODO: VPOPCNTQ 7(AX)(CX*4), K2, Y1                       // 62f2fd2a558c8807000000
	//TODO: VPOPCNTQ 7(AX)(CX*1), K2, Y1                       // 62f2fd2a558c0807000000
	//TODO: VPOPCNTQ Z1, K2, Z20                               // 62e2fd4a55e1
	//TODO: VPOPCNTQ Z3, K2, Z20                               // 62e2fd4a55e3
	//TODO: VPOPCNTQ 17(SP), K2, Z20                           // 62e2fd4a55a42411000000
	//TODO: VPOPCNTQ -17(BP)(SI*4), K2, Z20                    // 62e2fd4a55a4b5efffffff
	//TODO: VPOPCNTQ Z1, K2, Z9                                // 6272fd4a55c9
	//TODO: VPOPCNTQ Z3, K2, Z9                                // 6272fd4a55cb
	//TODO: VPOPCNTQ 17(SP), K2, Z9                            // 6272fd4a558c2411000000
	//TODO: VPOPCNTQ -17(BP)(SI*4), K2, Z9                     // 6272fd4a558cb5efffffff
	RET
