// Code generated by avx512test. DO NOT EDIT.

#include "../../../../../../runtime/textflag.h"

TEXT asmtest_avx512er(SB), NOSPLIT, $0
	//TODO: VEXP2PD Z17, K7, Z20                               // 62a2fd4fc8e1
	//TODO: VEXP2PD Z0, K7, Z20                                // 62e2fd4fc8e0
	//TODO: VEXP2PD Z17, K7, Z0                                // 62b2fd4fc8c1
	//TODO: VEXP2PD Z0, K7, Z0                                 // 62f2fd4fc8c0
	//TODO: VEXP2PD Z31, K2, Z17                               // 6282fd4ac8cf
	//TODO: VEXP2PD Z0, K2, Z17                                // 62e2fd4ac8c8
	//TODO: VEXP2PD (R14), K2, Z17                             // 62c2fd4ac80e
	//TODO: VEXP2PD -7(DI)(R8*8), K2, Z17                      // 62a2fd4ac88cc7f9ffffff
	//TODO: VEXP2PD Z31, K2, Z23                               // 6282fd4ac8ff
	//TODO: VEXP2PD Z0, K2, Z23                                // 62e2fd4ac8f8
	//TODO: VEXP2PD (R14), K2, Z23                             // 62c2fd4ac83e
	//TODO: VEXP2PD -7(DI)(R8*8), K2, Z23                      // 62a2fd4ac8bcc7f9ffffff
	//TODO: VEXP2PS Z6, K4, Z21                                // 62e27d4cc8ee
	//TODO: VEXP2PS Z9, K4, Z21                                // 62c27d4cc8e9
	//TODO: VEXP2PS Z6, K4, Z9                                 // 62727d4cc8ce
	//TODO: VEXP2PS Z9, K4, Z9                                 // 62527d4cc8c9
	//TODO: VEXP2PS Z20, K1, Z1                                // 62b27d49c8cc
	//TODO: VEXP2PS Z9, K1, Z1                                 // 62d27d49c8c9
	//TODO: VEXP2PS 99(R15)(R15*4), K1, Z1                     // 62927d49c88cbf63000000
	//TODO: VEXP2PS 15(DX), K1, Z1                             // 62f27d49c88a0f000000
	//TODO: VEXP2PS Z20, K1, Z9                                // 62327d49c8cc
	//TODO: VEXP2PS Z9, K1, Z9                                 // 62527d49c8c9
	//TODO: VEXP2PS 99(R15)(R15*4), K1, Z9                     // 62127d49c88cbf63000000
	//TODO: VEXP2PS 15(DX), K1, Z9                             // 62727d49c88a0f000000
	//TODO: VRCP28PD Z13, K7, Z11                              // 6252fd4fcadd
	//TODO: VRCP28PD Z14, K7, Z11                              // 6252fd4fcade
	//TODO: VRCP28PD Z13, K7, Z5                               // 62d2fd4fcaed
	//TODO: VRCP28PD Z14, K7, Z5                               // 62d2fd4fcaee
	//TODO: VRCP28PD Z2, K2, Z5                                // 62f2fd4acaea
	//TODO: VRCP28PD -7(CX)(DX*1), K2, Z5                      // 62f2fd4acaac11f9ffffff
	//TODO: VRCP28PD -15(R14)(R15*4), K2, Z5                   // 6292fd4acaacbef1ffffff
	//TODO: VRCP28PD Z2, K2, Z23                               // 62e2fd4acafa
	//TODO: VRCP28PD -7(CX)(DX*1), K2, Z23                     // 62e2fd4acabc11f9ffffff
	//TODO: VRCP28PD -15(R14)(R15*4), K2, Z23                  // 6282fd4acabcbef1ffffff
	//TODO: VRCP28PS Z26, K5, Z6                               // 62927d4dcaf2
	//TODO: VRCP28PS Z14, K5, Z6                               // 62d27d4dcaf6
	//TODO: VRCP28PS Z26, K5, Z14                              // 62127d4dcaf2
	//TODO: VRCP28PS Z14, K5, Z14                              // 62527d4dcaf6
	//TODO: VRCP28PS Z13, K3, Z28                              // 62427d4bcae5
	//TODO: VRCP28PS Z21, K3, Z28                              // 62227d4bcae5
	//TODO: VRCP28PS 15(DX)(BX*1), K3, Z28                     // 62627d4bcaa41a0f000000
	//TODO: VRCP28PS -7(CX)(DX*2), K3, Z28                     // 62627d4bcaa451f9ffffff
	//TODO: VRCP28PS Z13, K3, Z6                               // 62d27d4bcaf5
	//TODO: VRCP28PS Z21, K3, Z6                               // 62b27d4bcaf5
	//TODO: VRCP28PS 15(DX)(BX*1), K3, Z6                      // 62f27d4bcab41a0f000000
	//TODO: VRCP28PS -7(CX)(DX*2), K3, Z6                      // 62f27d4bcab451f9ffffff
	//TODO: VRCP28SD X8, X18, K4, X0                           // 62d2ed04cbc0
	//TODO: VRCP28SD X3, X25, K2, X27                          // 6262b502cbdb or 6262b522cbdb or 6262b542cbdb
	//TODO: VRCP28SD 17(SP)(BP*8), X25, K2, X27                // 6262b502cb9cec11000000 or 6262b522cb9cec11000000 or 6262b542cb9cec11000000
	//TODO: VRCP28SD 17(SP)(BP*4), X25, K2, X27                // 6262b502cb9cac11000000 or 6262b522cb9cac11000000 or 6262b542cb9cac11000000
	//TODO: VRCP28SS X28, X15, K2, X18                         // 6282050acbd4
	//TODO: VRCP28SS X13, X7, K3, X15                          // 6252450bcbfd or 6252452bcbfd or 6252454bcbfd
	//TODO: VRCP28SS -7(CX), X7, K3, X15                       // 6272450bcbb9f9ffffff or 6272452bcbb9f9ffffff or 6272454bcbb9f9ffffff
	//TODO: VRCP28SS 15(DX)(BX*4), X7, K3, X15                 // 6272450bcbbc9a0f000000 or 6272452bcbbc9a0f000000 or 6272454bcbbc9a0f000000
	//TODO: VRSQRT28PD Z7, K3, Z3                              // 62f2fd4bccdf
	//TODO: VRSQRT28PD Z9, K3, Z3                              // 62d2fd4bccd9
	//TODO: VRSQRT28PD Z7, K3, Z27                             // 6262fd4bccdf
	//TODO: VRSQRT28PD Z9, K3, Z27                             // 6242fd4bccd9
	//TODO: VRSQRT28PD Z20, K3, Z0                             // 62b2fd4bccc4
	//TODO: VRSQRT28PD Z28, K3, Z0                             // 6292fd4bccc4
	//TODO: VRSQRT28PD (SI), K3, Z0                            // 62f2fd4bcc06
	//TODO: VRSQRT28PD 7(SI)(DI*2), K3, Z0                     // 62f2fd4bcc847e07000000
	//TODO: VRSQRT28PD Z20, K3, Z6                             // 62b2fd4bccf4
	//TODO: VRSQRT28PD Z28, K3, Z6                             // 6292fd4bccf4
	//TODO: VRSQRT28PD (SI), K3, Z6                            // 62f2fd4bcc36
	//TODO: VRSQRT28PD 7(SI)(DI*2), K3, Z6                     // 62f2fd4bccb47e07000000
	//TODO: VRSQRT28PS Z9, K2, Z3                              // 62d27d4accd9
	//TODO: VRSQRT28PS Z19, K2, Z3                             // 62b27d4accdb
	//TODO: VRSQRT28PS Z9, K2, Z30                             // 62427d4accf1
	//TODO: VRSQRT28PS Z19, K2, Z30                            // 62227d4accf3
	//TODO: VRSQRT28PS Z11, K1, Z12                            // 62527d49cce3
	//TODO: VRSQRT28PS Z5, K1, Z12                             // 62727d49cce5
	//TODO: VRSQRT28PS 17(SP)(BP*8), K1, Z12                   // 62727d49cca4ec11000000
	//TODO: VRSQRT28PS 17(SP)(BP*4), K1, Z12                   // 62727d49cca4ac11000000
	//TODO: VRSQRT28PS Z11, K1, Z22                            // 62c27d49ccf3
	//TODO: VRSQRT28PS Z5, K1, Z22                             // 62e27d49ccf5
	//TODO: VRSQRT28PS 17(SP)(BP*8), K1, Z22                   // 62e27d49ccb4ec11000000
	//TODO: VRSQRT28PS 17(SP)(BP*4), K1, Z22                   // 62e27d49ccb4ac11000000
	//TODO: VRSQRT28SD X0, X14, K2, X2                         // 62f28d0acdd0
	//TODO: VRSQRT28SD X11, X25, K1, X0                        // 62d2b501cdc3 or 62d2b521cdc3 or 62d2b541cdc3
	//TODO: VRSQRT28SD 99(R15)(R15*1), X25, K1, X0             // 6292b501cd843f63000000 or 6292b521cd843f63000000 or 6292b541cd843f63000000
	//TODO: VRSQRT28SD (DX), X25, K1, X0                       // 62f2b501cd02 or 62f2b521cd02 or 62f2b541cd02
	//TODO: VRSQRT28SS X11, X18, K7, X17                       // 62c26d07cdcb
	//TODO: VRSQRT28SS X24, X2, K1, X9                         // 62126d09cdc8 or 62126d29cdc8 or 62126d49cdc8
	//TODO: VRSQRT28SS 15(R8)(R14*4), X2, K1, X9               // 62126d09cd8cb00f000000 or 62126d29cd8cb00f000000 or 62126d49cd8cb00f000000
	//TODO: VRSQRT28SS -7(CX)(DX*4), X2, K1, X9                // 62726d09cd8c91f9ffffff or 62726d29cd8c91f9ffffff or 62726d49cd8c91f9ffffff
	RET
