// Code generated by avx512test. DO NOT EDIT.

#include "../../../../../../runtime/textflag.h"

TEXT asmtest_avx512dq(SB), NOSPLIT, $0
	//TODO: KADDB K3, K1, K6                                   // c5f54af3
	//TODO: KADDB K1, K1, K6                                   // c5f54af1
	//TODO: KADDB K3, K5, K6                                   // c5d54af3
	//TODO: KADDB K1, K5, K6                                   // c5d54af1
	//TODO: KADDB K3, K1, K5                                   // c5f54aeb
	//TODO: KADDB K1, K1, K5                                   // c5f54ae9
	//TODO: KADDB K3, K5, K5                                   // c5d54aeb
	//TODO: KADDB K1, K5, K5                                   // c5d54ae9
	//TODO: KADDW K6, K6, K1                                   // c5cc4ace
	//TODO: KADDW K4, K6, K1                                   // c5cc4acc
	//TODO: KADDW K6, K7, K1                                   // c5c44ace
	//TODO: KADDW K4, K7, K1                                   // c5c44acc
	//TODO: KADDW K6, K6, K3                                   // c5cc4ade
	//TODO: KADDW K4, K6, K3                                   // c5cc4adc
	//TODO: KADDW K6, K7, K3                                   // c5c44ade
	//TODO: KADDW K4, K7, K3                                   // c5c44adc
	//TODO: KANDB K2, K4, K4                                   // c5dd41e2
	//TODO: KANDB K7, K4, K4                                   // c5dd41e7
	//TODO: KANDB K2, K5, K4                                   // c5d541e2
	//TODO: KANDB K7, K5, K4                                   // c5d541e7
	//TODO: KANDB K2, K4, K6                                   // c5dd41f2
	//TODO: KANDB K7, K4, K6                                   // c5dd41f7
	//TODO: KANDB K2, K5, K6                                   // c5d541f2
	//TODO: KANDB K7, K5, K6                                   // c5d541f7
	//TODO: KANDNB K7, K5, K3                                  // c5d542df
	//TODO: KANDNB K6, K5, K3                                  // c5d542de
	//TODO: KANDNB K7, K4, K3                                  // c5dd42df
	//TODO: KANDNB K6, K4, K3                                  // c5dd42de
	//TODO: KANDNB K7, K5, K1                                  // c5d542cf
	//TODO: KANDNB K6, K5, K1                                  // c5d542ce
	//TODO: KANDNB K7, K4, K1                                  // c5dd42cf
	//TODO: KANDNB K6, K4, K1                                  // c5dd42ce
	//TODO: KMOVB K7, 17(SP)                                   // c5f9917c2411
	//TODO: KMOVB K6, 17(SP)                                   // c5f991742411
	//TODO: KMOVB K7, -17(BP)(SI*4)                            // c5f9917cb5ef
	//TODO: KMOVB K6, -17(BP)(SI*4)                            // c5f99174b5ef
	//TODO: KMOVB K4, AX                                       // c5f993c4
	//TODO: KMOVB K6, AX                                       // c5f993c6
	//TODO: KMOVB K4, R9                                       // c57993cc
	//TODO: KMOVB K6, R9                                       // c57993ce
	//TODO: KMOVB K5, K0                                       // c5f990c5
	//TODO: KMOVB K4, K0                                       // c5f990c4
	//TODO: KMOVB 7(AX), K0                                    // c5f9904007
	//TODO: KMOVB (DI), K0                                     // c5f99007
	//TODO: KMOVB K5, K7                                       // c5f990fd
	//TODO: KMOVB K4, K7                                       // c5f990fc
	//TODO: KMOVB 7(AX), K7                                    // c5f9907807
	//TODO: KMOVB (DI), K7                                     // c5f9903f
	//TODO: KMOVB CX, K4                                       // c5f992e1
	//TODO: KMOVB SP, K4                                       // c5f992e4
	//TODO: KMOVB CX, K6                                       // c5f992f1
	//TODO: KMOVB SP, K6                                       // c5f992f4
	//TODO: KNOTB K1, K4                                       // c5f944e1
	//TODO: KNOTB K3, K4                                       // c5f944e3
	//TODO: KNOTB K1, K6                                       // c5f944f1
	//TODO: KNOTB K3, K6                                       // c5f944f3
	//TODO: KORB K3, K1, K6                                    // c5f545f3
	//TODO: KORB K1, K1, K6                                    // c5f545f1
	//TODO: KORB K3, K5, K6                                    // c5d545f3
	//TODO: KORB K1, K5, K6                                    // c5d545f1
	//TODO: KORB K3, K1, K5                                    // c5f545eb
	//TODO: KORB K1, K1, K5                                    // c5f545e9
	//TODO: KORB K3, K5, K5                                    // c5d545eb
	//TODO: KORB K1, K5, K5                                    // c5d545e9
	//TODO: KORTESTB K6, K1                                    // c5f998ce
	//TODO: KORTESTB K7, K1                                    // c5f998cf
	//TODO: KORTESTB K6, K3                                    // c5f998de
	//TODO: KORTESTB K7, K3                                    // c5f998df
	//TODO: KSHIFTLB $127, K4, K7                              // c4e37932fc7f
	//TODO: KSHIFTLB $127, K6, K7                              // c4e37932fe7f
	//TODO: KSHIFTLB $127, K4, K6                              // c4e37932f47f
	//TODO: KSHIFTLB $127, K6, K6                              // c4e37932f67f
	//TODO: KSHIFTRB $42, K4, K4                               // c4e37930e42a
	//TODO: KSHIFTRB $42, K5, K4                               // c4e37930e52a
	//TODO: KSHIFTRB $42, K4, K6                               // c4e37930f42a
	//TODO: KSHIFTRB $42, K5, K6                               // c4e37930f52a
	//TODO: KTESTB K4, K7                                      // c5f999fc
	//TODO: KTESTB K6, K7                                      // c5f999fe
	//TODO: KTESTB K4, K6                                      // c5f999f4
	//TODO: KTESTB K6, K6                                      // c5f999f6
	//TODO: KTESTW K6, K6                                      // c5f899f6
	//TODO: KTESTW K4, K6                                      // c5f899f4
	//TODO: KTESTW K6, K7                                      // c5f899fe
	//TODO: KTESTW K4, K7                                      // c5f899fc
	//TODO: KXNORB K5, K0, K4                                  // c5fd46e5
	//TODO: KXNORB K4, K0, K4                                  // c5fd46e4
	//TODO: KXNORB K5, K7, K4                                  // c5c546e5
	//TODO: KXNORB K4, K7, K4                                  // c5c546e4
	//TODO: KXNORB K5, K0, K6                                  // c5fd46f5
	//TODO: KXNORB K4, K0, K6                                  // c5fd46f4
	//TODO: KXNORB K5, K7, K6                                  // c5c546f5
	//TODO: KXNORB K4, K7, K6                                  // c5c546f4
	//TODO: KXORB K5, K3, K1                                   // c5e547cd
	//TODO: KXORB K4, K3, K1                                   // c5e547cc
	//TODO: KXORB K5, K1, K1                                   // c5f547cd
	//TODO: KXORB K4, K1, K1                                   // c5f547cc
	//TODO: KXORB K5, K3, K5                                   // c5e547ed
	//TODO: KXORB K4, K3, K5                                   // c5e547ec
	//TODO: KXORB K5, K1, K5                                   // c5f547ed
	//TODO: KXORB K4, K1, K5                                   // c5f547ec
	//TODO: VANDNPD X12, X15, K4, X9                           // 6251850c55cc
	//TODO: VANDNPD (R8), X15, K4, X9                          // 6251850c5508
	//TODO: VANDNPD 15(DX)(BX*2), X15, K4, X9                  // 6271850c558c5a0f000000
	//TODO: VANDNPD Y31, Y19, K5, Y5                           // 6291e52555ef
	//TODO: VANDNPD 99(R15)(R15*8), Y19, K5, Y5                // 6291e52555acff63000000
	//TODO: VANDNPD 7(AX)(CX*8), Y19, K5, Y5                   // 62f1e52555acc807000000
	//TODO: VANDNPD Z20, Z0, K7, Z7                            // 62b1fd4f55fc
	//TODO: VANDNPD Z28, Z0, K7, Z7                            // 6291fd4f55fc
	//TODO: VANDNPD 99(R15)(R15*8), Z0, K7, Z7                 // 6291fd4f55bcff63000000
	//TODO: VANDNPD 7(AX)(CX*8), Z0, K7, Z7                    // 62f1fd4f55bcc807000000
	//TODO: VANDNPD Z20, Z6, K7, Z7                            // 62b1cd4f55fc
	//TODO: VANDNPD Z28, Z6, K7, Z7                            // 6291cd4f55fc
	//TODO: VANDNPD 99(R15)(R15*8), Z6, K7, Z7                 // 6291cd4f55bcff63000000
	//TODO: VANDNPD 7(AX)(CX*8), Z6, K7, Z7                    // 62f1cd4f55bcc807000000
	//TODO: VANDNPD Z20, Z0, K7, Z9                            // 6231fd4f55cc
	//TODO: VANDNPD Z28, Z0, K7, Z9                            // 6211fd4f55cc
	//TODO: VANDNPD 99(R15)(R15*8), Z0, K7, Z9                 // 6211fd4f558cff63000000
	//TODO: VANDNPD 7(AX)(CX*8), Z0, K7, Z9                    // 6271fd4f558cc807000000
	//TODO: VANDNPD Z20, Z6, K7, Z9                            // 6231cd4f55cc
	//TODO: VANDNPD Z28, Z6, K7, Z9                            // 6211cd4f55cc
	//TODO: VANDNPD 99(R15)(R15*8), Z6, K7, Z9                 // 6211cd4f558cff63000000
	//TODO: VANDNPD 7(AX)(CX*8), Z6, K7, Z9                    // 6271cd4f558cc807000000
	//TODO: VANDNPS X14, X12, K7, X0                           // 62d11c0f55c6
	//TODO: VANDNPS 17(SP)(BP*1), X12, K7, X0                  // 62f11c0f55842c11000000
	//TODO: VANDNPS -7(CX)(DX*8), X12, K7, X0                  // 62f11c0f5584d1f9ffffff
	//TODO: VANDNPS Y24, Y2, K6, Y28                           // 62016c2e55e0
	//TODO: VANDNPS (AX), Y2, K6, Y28                          // 62616c2e5520
	//TODO: VANDNPS 7(SI), Y2, K6, Y28                         // 62616c2e55a607000000
	//TODO: VANDNPS Z12, Z9, K3, Z3                            // 62d1344b55dc
	//TODO: VANDNPS Z22, Z9, K3, Z3                            // 62b1344b55de
	//TODO: VANDNPS (AX), Z9, K3, Z3                           // 62f1344b5518
	//TODO: VANDNPS 7(SI), Z9, K3, Z3                          // 62f1344b559e07000000
	//TODO: VANDNPS Z12, Z19, K3, Z3                           // 62d1644355dc
	//TODO: VANDNPS Z22, Z19, K3, Z3                           // 62b1644355de
	//TODO: VANDNPS (AX), Z19, K3, Z3                          // 62f164435518
	//TODO: VANDNPS 7(SI), Z19, K3, Z3                         // 62f16443559e07000000
	//TODO: VANDNPS Z12, Z9, K3, Z30                           // 6241344b55f4
	//TODO: VANDNPS Z22, Z9, K3, Z30                           // 6221344b55f6
	//TODO: VANDNPS (AX), Z9, K3, Z30                          // 6261344b5530
	//TODO: VANDNPS 7(SI), Z9, K3, Z30                         // 6261344b55b607000000
	//TODO: VANDNPS Z12, Z19, K3, Z30                          // 6241644355f4
	//TODO: VANDNPS Z22, Z19, K3, Z30                          // 6221644355f6
	//TODO: VANDNPS (AX), Z19, K3, Z30                         // 626164435530
	//TODO: VANDNPS 7(SI), Z19, K3, Z30                        // 6261644355b607000000
	//TODO: VANDPD X15, X17, K7, X5                            // 62d1f50754ef
	//TODO: VANDPD -17(BP)(SI*2), X17, K7, X5                  // 62f1f50754ac75efffffff
	//TODO: VANDPD 7(AX)(CX*2), X17, K7, X5                    // 62f1f50754ac4807000000
	//TODO: VANDPD Y11, Y0, K4, Y27                            // 6241fd2c54db
	//TODO: VANDPD (BX), Y0, K4, Y27                           // 6261fd2c541b
	//TODO: VANDPD -17(BP)(SI*1), Y0, K4, Y27                  // 6261fd2c549c35efffffff
	//TODO: VANDPD Z2, Z18, K4, Z11                            // 6271ed4454da
	//TODO: VANDPD Z21, Z18, K4, Z11                           // 6231ed4454dd
	//TODO: VANDPD (BX), Z18, K4, Z11                          // 6271ed44541b
	//TODO: VANDPD -17(BP)(SI*1), Z18, K4, Z11                 // 6271ed44549c35efffffff
	//TODO: VANDPD Z2, Z24, K4, Z11                            // 6271bd4454da
	//TODO: VANDPD Z21, Z24, K4, Z11                           // 6231bd4454dd
	//TODO: VANDPD (BX), Z24, K4, Z11                          // 6271bd44541b
	//TODO: VANDPD -17(BP)(SI*1), Z24, K4, Z11                 // 6271bd44549c35efffffff
	//TODO: VANDPD Z2, Z18, K4, Z5                             // 62f1ed4454ea
	//TODO: VANDPD Z21, Z18, K4, Z5                            // 62b1ed4454ed
	//TODO: VANDPD (BX), Z18, K4, Z5                           // 62f1ed44542b
	//TODO: VANDPD -17(BP)(SI*1), Z18, K4, Z5                  // 62f1ed4454ac35efffffff
	//TODO: VANDPD Z2, Z24, K4, Z5                             // 62f1bd4454ea
	//TODO: VANDPD Z21, Z24, K4, Z5                            // 62b1bd4454ed
	//TODO: VANDPD (BX), Z24, K4, Z5                           // 62f1bd44542b
	//TODO: VANDPD -17(BP)(SI*1), Z24, K4, Z5                  // 62f1bd4454ac35efffffff
	//TODO: VANDPS X26, X3, K7, X8                             // 6211640f54c2
	//TODO: VANDPS 15(R8)(R14*1), X3, K7, X8                   // 6211640f5484300f000000
	//TODO: VANDPS 15(R8)(R14*2), X3, K7, X8                   // 6211640f5484700f000000
	//TODO: VANDPS Y14, Y3, K2, Y31                            // 6241642a54fe
	//TODO: VANDPS 15(R8)(R14*4), Y3, K2, Y31                  // 6201642a54bcb00f000000
	//TODO: VANDPS -7(CX)(DX*4), Y3, K2, Y31                   // 6261642a54bc91f9ffffff
	//TODO: VANDPS Z6, Z6, K5, Z7                              // 62f14c4d54fe
	//TODO: VANDPS Z22, Z6, K5, Z7                             // 62b14c4d54fe
	//TODO: VANDPS 15(R8)(R14*4), Z6, K5, Z7                   // 62914c4d54bcb00f000000
	//TODO: VANDPS -7(CX)(DX*4), Z6, K5, Z7                    // 62f14c4d54bc91f9ffffff
	//TODO: VANDPS Z6, Z16, K5, Z7                             // 62f17c4554fe
	//TODO: VANDPS Z22, Z16, K5, Z7                            // 62b17c4554fe
	//TODO: VANDPS 15(R8)(R14*4), Z16, K5, Z7                  // 62917c4554bcb00f000000
	//TODO: VANDPS -7(CX)(DX*4), Z16, K5, Z7                   // 62f17c4554bc91f9ffffff
	//TODO: VANDPS Z6, Z6, K5, Z13                             // 62714c4d54ee
	//TODO: VANDPS Z22, Z6, K5, Z13                            // 62314c4d54ee
	//TODO: VANDPS 15(R8)(R14*4), Z6, K5, Z13                  // 62114c4d54acb00f000000
	//TODO: VANDPS -7(CX)(DX*4), Z6, K5, Z13                   // 62714c4d54ac91f9ffffff
	//TODO: VANDPS Z6, Z16, K5, Z13                            // 62717c4554ee
	//TODO: VANDPS Z22, Z16, K5, Z13                           // 62317c4554ee
	//TODO: VANDPS 15(R8)(R14*4), Z16, K5, Z13                 // 62117c4554acb00f000000
	//TODO: VANDPS -7(CX)(DX*4), Z16, K5, Z13                  // 62717c4554ac91f9ffffff
	//TODO: VBROADCASTF32X2 X26, K3, Y18                       // 62827d2b19d2
	//TODO: VBROADCASTF32X2 -17(BP)(SI*8), K3, Y18             // 62e27d2b1994f5efffffff
	//TODO: VBROADCASTF32X2 (R15), K3, Y18                     // 62c27d2b1917
	//TODO: VBROADCASTF32X2 X18, K2, Z1                        // 62b27d4a19ca
	//TODO: VBROADCASTF32X2 7(SI)(DI*8), K2, Z1                // 62f27d4a198cfe07000000
	//TODO: VBROADCASTF32X2 -15(R14), K2, Z1                   // 62d27d4a198ef1ffffff
	//TODO: VBROADCASTF32X2 X18, K2, Z3                        // 62b27d4a19da
	//TODO: VBROADCASTF32X2 7(SI)(DI*8), K2, Z3                // 62f27d4a199cfe07000000
	//TODO: VBROADCASTF32X2 -15(R14), K2, Z3                   // 62d27d4a199ef1ffffff
	//TODO: VBROADCASTF32X8 -17(BP)(SI*2), K1, Z28             // 62627d491ba475efffffff
	//TODO: VBROADCASTF32X8 7(AX)(CX*2), K1, Z28               // 62627d491ba44807000000
	//TODO: VBROADCASTF32X8 -17(BP)(SI*2), K1, Z13             // 62727d491bac75efffffff
	//TODO: VBROADCASTF32X8 7(AX)(CX*2), K1, Z13               // 62727d491bac4807000000
	//TODO: VBROADCASTF64X2 -7(CX)(DX*1), K7, Y9               // 6272fd2f1a8c11f9ffffff
	//TODO: VBROADCASTF64X2 -15(R14)(R15*4), K7, Y9            // 6212fd2f1a8cbef1ffffff
	//TODO: VBROADCASTF64X2 15(DX)(BX*1), K1, Z14              // 6272fd491ab41a0f000000
	//TODO: VBROADCASTF64X2 -7(CX)(DX*2), K1, Z14              // 6272fd491ab451f9ffffff
	//TODO: VBROADCASTF64X2 15(DX)(BX*1), K1, Z28              // 6262fd491aa41a0f000000
	//TODO: VBROADCASTF64X2 -7(CX)(DX*2), K1, Z28              // 6262fd491aa451f9ffffff
	//TODO: VBROADCASTI32X2 X1, K1, X21                        // 62e27d0959e9
	//TODO: VBROADCASTI32X2 7(SI)(DI*1), K1, X21               // 62e27d0959ac3e07000000
	//TODO: VBROADCASTI32X2 15(DX)(BX*8), K1, X21              // 62e27d0959acda0f000000
	//TODO: VBROADCASTI32X2 X11, K7, Y3                        // 62d27d2f59db
	//TODO: VBROADCASTI32X2 -7(DI)(R8*1), K7, Y3               // 62b27d2f599c07f9ffffff
	//TODO: VBROADCASTI32X2 (SP), K7, Y3                       // 62f27d2f591c24
	//TODO: VBROADCASTI32X2 X31, K2, Z15                       // 62127d4a59ff
	//TODO: VBROADCASTI32X2 -7(CX), K2, Z15                    // 62727d4a59b9f9ffffff
	//TODO: VBROADCASTI32X2 15(DX)(BX*4), K2, Z15              // 62727d4a59bc9a0f000000
	//TODO: VBROADCASTI32X2 X31, K2, Z30                       // 62027d4a59f7
	//TODO: VBROADCASTI32X2 -7(CX), K2, Z30                    // 62627d4a59b1f9ffffff
	//TODO: VBROADCASTI32X2 15(DX)(BX*4), K2, Z30              // 62627d4a59b49a0f000000
	//TODO: VBROADCASTI32X8 (R14), K3, Z5                      // 62d27d4b5b2e
	//TODO: VBROADCASTI32X8 -7(DI)(R8*8), K3, Z5               // 62b27d4b5bacc7f9ffffff
	//TODO: VBROADCASTI32X8 (R14), K3, Z1                      // 62d27d4b5b0e
	//TODO: VBROADCASTI32X8 -7(DI)(R8*8), K3, Z1               // 62b27d4b5b8cc7f9ffffff
	//TODO: VBROADCASTI64X2 15(R8), K4, Y23                    // 62c2fd2c5ab80f000000
	//TODO: VBROADCASTI64X2 (BP), K4, Y23                      // 62e2fd2c5a7d00
	//TODO: VBROADCASTI64X2 15(R8)(R14*8), K5, Z3              // 6292fd4d5a9cf00f000000
	//TODO: VBROADCASTI64X2 -15(R14)(R15*2), K5, Z3            // 6292fd4d5a9c7ef1ffffff
	//TODO: VBROADCASTI64X2 15(R8)(R14*8), K5, Z5              // 6292fd4d5aacf00f000000
	//TODO: VBROADCASTI64X2 -15(R14)(R15*2), K5, Z5            // 6292fd4d5aac7ef1ffffff
	//TODO: VCVTPD2QQ X25, K7, X5                              // 6291fd0f7be9
	//TODO: VCVTPD2QQ -17(BP)(SI*8), K7, X5                    // 62f1fd0f7bacf5efffffff
	//TODO: VCVTPD2QQ (R15), K7, X5                            // 62d1fd0f7b2f
	//TODO: VCVTPD2QQ Y5, K2, Y3                               // 62f1fd2a7bdd
	//TODO: VCVTPD2QQ -15(R14)(R15*1), K2, Y3                  // 6291fd2a7b9c3ef1ffffff
	//TODO: VCVTPD2QQ -15(BX), K2, Y3                          // 62f1fd2a7b9bf1ffffff
	//TODO: VCVTPD2QQ Z12, K5, Z14                             // 6251fd4d7bf4
	//TODO: VCVTPD2QQ Z13, K5, Z14                             // 6251fd4d7bf5
	//TODO: VCVTPD2QQ Z12, K5, Z13                             // 6251fd4d7bec
	//TODO: VCVTPD2QQ Z13, K5, Z13                             // 6251fd4d7bed
	//TODO: VCVTPD2QQ Z2, K3, Z21                              // 62e1fd4b7bea
	//TODO: VCVTPD2QQ Z7, K3, Z21                              // 62e1fd4b7bef
	//TODO: VCVTPD2QQ -17(BP), K3, Z21                         // 62e1fd4b7badefffffff
	//TODO: VCVTPD2QQ -15(R14)(R15*8), K3, Z21                 // 6281fd4b7bacfef1ffffff
	//TODO: VCVTPD2QQ Z2, K3, Z9                               // 6271fd4b7bca
	//TODO: VCVTPD2QQ Z7, K3, Z9                               // 6271fd4b7bcf
	//TODO: VCVTPD2QQ -17(BP), K3, Z9                          // 6271fd4b7b8defffffff
	//TODO: VCVTPD2QQ -15(R14)(R15*8), K3, Z9                  // 6211fd4b7b8cfef1ffffff
	//TODO: VCVTPD2UQQ X8, K3, X2                              // 62d1fd0b79d0
	//TODO: VCVTPD2UQQ 7(SI)(DI*1), K3, X2                     // 62f1fd0b79943e07000000
	//TODO: VCVTPD2UQQ 15(DX)(BX*8), K3, X2                    // 62f1fd0b7994da0f000000
	//TODO: VCVTPD2UQQ Y13, K3, Y22                            // 62c1fd2b79f5
	//TODO: VCVTPD2UQQ (SI), K3, Y22                           // 62e1fd2b7936
	//TODO: VCVTPD2UQQ 7(SI)(DI*2), K3, Y22                    // 62e1fd2b79b47e07000000
	//TODO: VCVTPD2UQQ Z3, K2, Z27                             // 6261fd4a79db
	//TODO: VCVTPD2UQQ Z0, K2, Z27                             // 6261fd4a79d8
	//TODO: VCVTPD2UQQ Z3, K2, Z14                             // 6271fd4a79f3
	//TODO: VCVTPD2UQQ Z0, K2, Z14                             // 6271fd4a79f0
	//TODO: VCVTPD2UQQ Z8, K1, Z14                             // 6251fd4979f0
	//TODO: VCVTPD2UQQ Z24, K1, Z14                            // 6211fd4979f0
	//TODO: VCVTPD2UQQ 15(R8), K1, Z14                         // 6251fd4979b00f000000
	//TODO: VCVTPD2UQQ (BP), K1, Z14                           // 6271fd49797500
	//TODO: VCVTPD2UQQ Z8, K1, Z7                              // 62d1fd4979f8
	//TODO: VCVTPD2UQQ Z24, K1, Z7                             // 6291fd4979f8
	//TODO: VCVTPD2UQQ 15(R8), K1, Z7                          // 62d1fd4979b80f000000
	//TODO: VCVTPD2UQQ (BP), K1, Z7                            // 62f1fd49797d00
	//TODO: VCVTPS2QQ X0, K3, X11                              // 62717d0b7bd8
	//TODO: VCVTPS2QQ (BX), K3, X11                            // 62717d0b7b1b
	//TODO: VCVTPS2QQ -17(BP)(SI*1), K3, X11                   // 62717d0b7b9c35efffffff
	//TODO: VCVTPS2QQ X18, K7, Y7                              // 62b17d2f7bfa
	//TODO: VCVTPS2QQ 99(R15)(R15*1), K7, Y7                   // 62917d2f7bbc3f63000000
	//TODO: VCVTPS2QQ (DX), K7, Y7                             // 62f17d2f7b3a
	//TODO: VCVTPS2QQ Y2, K4, Z6                               // 62f17d4c7bf2
	//TODO: VCVTPS2QQ Y2, K4, Z14                              // 62717d4c7bf2
	//TODO: VCVTPS2QQ Y21, K4, Z26                             // 62217d4c7bd5
	//TODO: VCVTPS2QQ 7(AX)(CX*4), K4, Z26                     // 62617d4c7b948807000000
	//TODO: VCVTPS2QQ 7(AX)(CX*1), K4, Z26                     // 62617d4c7b940807000000
	//TODO: VCVTPS2QQ Y21, K4, Z14                             // 62317d4c7bf5
	//TODO: VCVTPS2QQ 7(AX)(CX*4), K4, Z14                     // 62717d4c7bb48807000000
	//TODO: VCVTPS2QQ 7(AX)(CX*1), K4, Z14                     // 62717d4c7bb40807000000
	//TODO: VCVTPS2UQQ X3, K4, X25                             // 62617d0c79cb
	//TODO: VCVTPS2UQQ (R8), K4, X25                           // 62417d0c7908
	//TODO: VCVTPS2UQQ 15(DX)(BX*2), K4, X25                   // 62617d0c798c5a0f000000
	//TODO: VCVTPS2UQQ X18, K2, Y1                             // 62b17d2a79ca
	//TODO: VCVTPS2UQQ 7(SI)(DI*8), K2, Y1                     // 62f17d2a798cfe07000000
	//TODO: VCVTPS2UQQ -15(R14), K2, Y1                        // 62d17d2a798ef1ffffff
	//TODO: VCVTPS2UQQ Y9, K2, Z21                             // 62c17d4a79e9
	//TODO: VCVTPS2UQQ Y9, K2, Z13                             // 62517d4a79e9
	//TODO: VCVTPS2UQQ Y3, K3, Z11                             // 62717d4b79db
	//TODO: VCVTPS2UQQ 17(SP)(BP*8), K3, Z11                   // 62717d4b799cec11000000
	//TODO: VCVTPS2UQQ 17(SP)(BP*4), K3, Z11                   // 62717d4b799cac11000000
	//TODO: VCVTPS2UQQ Y3, K3, Z25                             // 62617d4b79cb
	//TODO: VCVTPS2UQQ 17(SP)(BP*8), K3, Z25                   // 62617d4b798cec11000000
	//TODO: VCVTPS2UQQ 17(SP)(BP*4), K3, Z25                   // 62617d4b798cac11000000
	//TODO: VCVTQQ2PD X28, K3, X15                             // 6211fe0be6fc
	//TODO: VCVTQQ2PD 17(SP)(BP*1), K3, X15                    // 6271fe0be6bc2c11000000
	//TODO: VCVTQQ2PD -7(CX)(DX*8), K3, X15                    // 6271fe0be6bcd1f9ffffff
	//TODO: VCVTQQ2PD Y9, K3, Y2                               // 62d1fe2be6d1
	//TODO: VCVTQQ2PD 7(SI)(DI*1), K3, Y2                      // 62f1fe2be6943e07000000
	//TODO: VCVTQQ2PD 15(DX)(BX*8), K3, Y2                     // 62f1fe2be694da0f000000
	//TODO: VCVTQQ2PD Z27, K2, Z3                              // 6291fe4ae6db
	//TODO: VCVTQQ2PD Z15, K2, Z3                              // 62d1fe4ae6df
	//TODO: VCVTQQ2PD Z27, K2, Z12                             // 6211fe4ae6e3
	//TODO: VCVTQQ2PD Z15, K2, Z12                             // 6251fe4ae6e7
	//TODO: VCVTQQ2PD Z23, K1, Z23                             // 62a1fe49e6ff
	//TODO: VCVTQQ2PD Z6, K1, Z23                              // 62e1fe49e6fe
	//TODO: VCVTQQ2PD 7(SI)(DI*4), K1, Z23                     // 62e1fe49e6bcbe07000000
	//TODO: VCVTQQ2PD -7(DI)(R8*2), K1, Z23                    // 62a1fe49e6bc47f9ffffff
	//TODO: VCVTQQ2PD Z23, K1, Z5                              // 62b1fe49e6ef
	//TODO: VCVTQQ2PD Z6, K1, Z5                               // 62f1fe49e6ee
	//TODO: VCVTQQ2PD 7(SI)(DI*4), K1, Z5                      // 62f1fe49e6acbe07000000
	//TODO: VCVTQQ2PD -7(DI)(R8*2), K1, Z5                     // 62b1fe49e6ac47f9ffffff
	//TODO: VCVTQQ2PS Z8, K2, Y12                              // 6251fc4a5be0
	//TODO: VCVTQQ2PS Z28, K2, Y12                             // 6211fc4a5be4
	//TODO: VCVTQQ2PS Z21, K1, Y21                             // 62a1fc495bed
	//TODO: VCVTQQ2PS Z5, K1, Y21                              // 62e1fc495bed
	//TODO: VCVTQQ2PS 17(SP), K1, Y21                          // 62e1fc495bac2411000000
	//TODO: VCVTQQ2PS -17(BP)(SI*4), K1, Y21                   // 62e1fc495bacb5efffffff
	//TODO: VCVTQQ2PSX X7, K7, X15                             // 6271fc0f5bff
	//TODO: VCVTQQ2PSX -17(BP)(SI*2), K7, X15                  // 6271fc0f5bbc75efffffff
	//TODO: VCVTQQ2PSX 7(AX)(CX*2), K7, X15                    // 6271fc0f5bbc4807000000
	//TODO: VCVTQQ2PSY Y14, K1, X13                            // 6251fc295bee
	//TODO: VCVTQQ2PSY -7(DI)(R8*1), K1, X13                   // 6231fc295bac07f9ffffff
	//TODO: VCVTQQ2PSY (SP), K1, X13                           // 6271fc295b2c24
	//TODO: VCVTTPD2QQ X25, K5, X0                             // 6291fd0d7ac1
	//TODO: VCVTTPD2QQ (R14), K5, X0                           // 62d1fd0d7a06
	//TODO: VCVTTPD2QQ -7(DI)(R8*8), K5, X0                    // 62b1fd0d7a84c7f9ffffff
	//TODO: VCVTTPD2QQ Y1, K7, Y16                             // 62e1fd2f7ac1
	//TODO: VCVTTPD2QQ 99(R15)(R15*8), K7, Y16                 // 6281fd2f7a84ff63000000
	//TODO: VCVTTPD2QQ 7(AX)(CX*8), K7, Y16                    // 62e1fd2f7a84c807000000
	//TODO: VCVTTPD2QQ Z6, K7, Z22                             // 62e1fd4f7af6
	//TODO: VCVTTPD2QQ Z8, K7, Z22                             // 62c1fd4f7af0
	//TODO: VCVTTPD2QQ Z6, K7, Z11                             // 6271fd4f7ade
	//TODO: VCVTTPD2QQ Z8, K7, Z11                             // 6251fd4f7ad8
	//TODO: VCVTTPD2QQ Z12, K6, Z25                            // 6241fd4e7acc
	//TODO: VCVTTPD2QQ Z17, K6, Z25                            // 6221fd4e7ac9
	//TODO: VCVTTPD2QQ 99(R15)(R15*1), K6, Z25                 // 6201fd4e7a8c3f63000000
	//TODO: VCVTTPD2QQ (DX), K6, Z25                           // 6261fd4e7a0a
	//TODO: VCVTTPD2QQ Z12, K6, Z12                            // 6251fd4e7ae4
	//TODO: VCVTTPD2QQ Z17, K6, Z12                            // 6231fd4e7ae1
	//TODO: VCVTTPD2QQ 99(R15)(R15*1), K6, Z12                 // 6211fd4e7aa43f63000000
	//TODO: VCVTTPD2QQ (DX), K6, Z12                           // 6271fd4e7a22
	//TODO: VCVTTPD2UQQ X9, K7, X11                            // 6251fd0f78d9
	//TODO: VCVTTPD2UQQ (CX), K7, X11                          // 6271fd0f7819
	//TODO: VCVTTPD2UQQ 99(R15), K7, X11                       // 6251fd0f789f63000000
	//TODO: VCVTTPD2UQQ Y21, K2, Y6                            // 62b1fd2a78f5
	//TODO: VCVTTPD2UQQ (BX), K2, Y6                           // 62f1fd2a7833
	//TODO: VCVTTPD2UQQ -17(BP)(SI*1), K2, Y6                  // 62f1fd2a78b435efffffff
	//TODO: VCVTTPD2UQQ Z8, K5, Z3                             // 62d1fd4d78d8
	//TODO: VCVTTPD2UQQ Z2, K5, Z3                             // 62f1fd4d78da
	//TODO: VCVTTPD2UQQ Z8, K5, Z21                            // 62c1fd4d78e8
	//TODO: VCVTTPD2UQQ Z2, K5, Z21                            // 62e1fd4d78ea
	//TODO: VCVTTPD2UQQ Z7, K3, Z3                             // 62f1fd4b78df
	//TODO: VCVTTPD2UQQ Z9, K3, Z3                             // 62d1fd4b78d9
	//TODO: VCVTTPD2UQQ 7(SI)(DI*8), K3, Z3                    // 62f1fd4b789cfe07000000
	//TODO: VCVTTPD2UQQ -15(R14), K3, Z3                       // 62d1fd4b789ef1ffffff
	//TODO: VCVTTPD2UQQ Z7, K3, Z27                            // 6261fd4b78df
	//TODO: VCVTTPD2UQQ Z9, K3, Z27                            // 6241fd4b78d9
	//TODO: VCVTTPD2UQQ 7(SI)(DI*8), K3, Z27                   // 6261fd4b789cfe07000000
	//TODO: VCVTTPD2UQQ -15(R14), K3, Z27                      // 6241fd4b789ef1ffffff
	//TODO: VCVTTPS2QQ X2, K3, X2                              // 62f17d0b7ad2
	//TODO: VCVTTPS2QQ -7(CX)(DX*1), K3, X2                    // 62f17d0b7a9411f9ffffff
	//TODO: VCVTTPS2QQ -15(R14)(R15*4), K3, X2                 // 62917d0b7a94bef1ffffff
	//TODO: VCVTTPS2QQ X27, K3, Y28                            // 62017d2b7ae3
	//TODO: VCVTTPS2QQ (R8), K3, Y28                           // 62417d2b7a20
	//TODO: VCVTTPS2QQ 15(DX)(BX*2), K3, Y28                   // 62617d2b7aa45a0f000000
	//TODO: VCVTTPS2QQ Y20, K2, Z12                            // 62317d4a7ae4
	//TODO: VCVTTPS2QQ Y20, K2, Z22                            // 62a17d4a7af4
	//TODO: VCVTTPS2QQ Y14, K1, Z11                            // 62517d497ade
	//TODO: VCVTTPS2QQ -7(DI)(R8*1), K1, Z11                   // 62317d497a9c07f9ffffff
	//TODO: VCVTTPS2QQ (SP), K1, Z11                           // 62717d497a1c24
	//TODO: VCVTTPS2QQ Y14, K1, Z5                             // 62d17d497aee
	//TODO: VCVTTPS2QQ -7(DI)(R8*1), K1, Z5                    // 62b17d497aac07f9ffffff
	//TODO: VCVTTPS2QQ (SP), K1, Z5                            // 62f17d497a2c24
	//TODO: VCVTTPS2UQQ X3, K1, X30                            // 62617d0978f3
	//TODO: VCVTTPS2UQQ -17(BP), K1, X30                       // 62617d0978b5efffffff
	//TODO: VCVTTPS2UQQ -15(R14)(R15*8), K1, X30               // 62017d0978b4fef1ffffff
	//TODO: VCVTTPS2UQQ X11, K1, Y20                           // 62c17d2978e3
	//TODO: VCVTTPS2UQQ -17(BP)(SI*2), K1, Y20                 // 62e17d2978a475efffffff
	//TODO: VCVTTPS2UQQ 7(AX)(CX*2), K1, Y20                   // 62e17d2978a44807000000
	//TODO: VCVTTPS2UQQ Y14, K7, Z6                            // 62d17d4f78f6
	//TODO: VCVTTPS2UQQ Y14, K7, Z22                           // 62c17d4f78f6
	//TODO: VCVTTPS2UQQ Y21, K2, Z1                            // 62b17d4a78cd
	//TODO: VCVTTPS2UQQ 99(R15)(R15*8), K2, Z1                 // 62917d4a788cff63000000
	//TODO: VCVTTPS2UQQ 7(AX)(CX*8), K2, Z1                    // 62f17d4a788cc807000000
	//TODO: VCVTTPS2UQQ Y21, K2, Z15                           // 62317d4a78fd
	//TODO: VCVTTPS2UQQ 99(R15)(R15*8), K2, Z15                // 62117d4a78bcff63000000
	//TODO: VCVTTPS2UQQ 7(AX)(CX*8), K2, Z15                   // 62717d4a78bcc807000000
	//TODO: VCVTUQQ2PD X16, K6, X0                             // 62b1fe0e7ac0
	//TODO: VCVTUQQ2PD 15(R8)(R14*8), K6, X0                   // 6291fe0e7a84f00f000000
	//TODO: VCVTUQQ2PD -15(R14)(R15*2), K6, X0                 // 6291fe0e7a847ef1ffffff
	//TODO: VCVTUQQ2PD Y3, K3, Y22                             // 62e1fe2b7af3
	//TODO: VCVTUQQ2PD 99(R15)(R15*4), K3, Y22                 // 6281fe2b7ab4bf63000000
	//TODO: VCVTUQQ2PD 15(DX), K3, Y22                         // 62e1fe2b7ab20f000000
	//TODO: VCVTUQQ2PD Z12, K7, Z1                             // 62d1fe4f7acc
	//TODO: VCVTUQQ2PD Z16, K7, Z1                             // 62b1fe4f7ac8
	//TODO: VCVTUQQ2PD Z12, K7, Z3                             // 62d1fe4f7adc
	//TODO: VCVTUQQ2PD Z16, K7, Z3                             // 62b1fe4f7ad8
	//TODO: VCVTUQQ2PD Z14, K4, Z28                            // 6241fe4c7ae6
	//TODO: VCVTUQQ2PD Z28, K4, Z28                            // 6201fe4c7ae4
	//TODO: VCVTUQQ2PD 15(R8)(R14*4), K4, Z28                  // 6201fe4c7aa4b00f000000
	//TODO: VCVTUQQ2PD -7(CX)(DX*4), K4, Z28                   // 6261fe4c7aa491f9ffffff
	//TODO: VCVTUQQ2PD Z14, K4, Z13                            // 6251fe4c7aee
	//TODO: VCVTUQQ2PD Z28, K4, Z13                            // 6211fe4c7aec
	//TODO: VCVTUQQ2PD 15(R8)(R14*4), K4, Z13                  // 6211fe4c7aacb00f000000
	//TODO: VCVTUQQ2PD -7(CX)(DX*4), K4, Z13                   // 6271fe4c7aac91f9ffffff
	//TODO: VCVTUQQ2PS Z3, K4, Y15                             // 6271ff4c7afb
	//TODO: VCVTUQQ2PS Z12, K4, Y15                            // 6251ff4c7afc
	//TODO: VCVTUQQ2PS Z15, K7, Y1                             // 62d1ff4f7acf
	//TODO: VCVTUQQ2PS Z30, K7, Y1                             // 6291ff4f7ace
	//TODO: VCVTUQQ2PS (R8), K7, Y1                            // 62d1ff4f7a08
	//TODO: VCVTUQQ2PS 15(DX)(BX*2), K7, Y1                    // 62f1ff4f7a8c5a0f000000
	//TODO: VCVTUQQ2PSX X0, K2, X21                            // 62e1ff0a7ae8
	//TODO: VCVTUQQ2PSX -15(R14)(R15*1), K2, X21               // 6281ff0a7aac3ef1ffffff
	//TODO: VCVTUQQ2PSX -15(BX), K2, X21                       // 62e1ff0a7aabf1ffffff
	//TODO: VCVTUQQ2PSY Y27, K5, X28                           // 6201ff2d7ae3
	//TODO: VCVTUQQ2PSY (CX), K5, X28                          // 6261ff2d7a21
	//TODO: VCVTUQQ2PSY 99(R15), K5, X28                       // 6241ff2d7aa763000000
	//TODO: VEXTRACTF32X8 $0, Z12, K4, Y24                     // 62137d4c1be000
	//TODO: VEXTRACTF32X8 $0, Z13, K4, Y24                     // 62137d4c1be800
	//TODO: VEXTRACTF32X8 $0, Z12, K4, 15(R8)                  // 62537d4c1ba00f00000000
	//TODO: VEXTRACTF32X8 $0, Z13, K4, 15(R8)                  // 62537d4c1ba80f00000000
	//TODO: VEXTRACTF32X8 $0, Z12, K4, (BP)                    // 62737d4c1b650000
	//TODO: VEXTRACTF32X8 $0, Z13, K4, (BP)                    // 62737d4c1b6d0000
	//TODO: VEXTRACTF64X2 $1, Y21, K4, X14                     // 62c3fd2c19ee01
	//TODO: VEXTRACTF64X2 $1, Y21, K4, -17(BP)(SI*8)           // 62e3fd2c19acf5efffffff01
	//TODO: VEXTRACTF64X2 $1, Y21, K4, (R15)                   // 62c3fd2c192f01
	//TODO: VEXTRACTF64X2 $0, Z21, K7, X5                      // 62e3fd4f19ed00
	//TODO: VEXTRACTF64X2 $0, Z9, K7, X5                       // 6273fd4f19cd00
	//TODO: VEXTRACTF64X2 $0, Z21, K7, 7(SI)(DI*8)             // 62e3fd4f19acfe0700000000
	//TODO: VEXTRACTF64X2 $0, Z9, K7, 7(SI)(DI*8)              // 6273fd4f198cfe0700000000
	//TODO: VEXTRACTF64X2 $0, Z21, K7, -15(R14)                // 62c3fd4f19aef1ffffff00
	//TODO: VEXTRACTF64X2 $0, Z9, K7, -15(R14)                 // 6253fd4f198ef1ffffff00
	//TODO: VEXTRACTI32X8 $1, Z23, K4, Y13                     // 62c37d4c3bfd01
	//TODO: VEXTRACTI32X8 $1, Z9, K4, Y13                      // 62537d4c3bcd01
	//TODO: VEXTRACTI32X8 $1, Z23, K4, -15(R14)(R15*1)         // 62837d4c3bbc3ef1ffffff01
	//TODO: VEXTRACTI32X8 $1, Z9, K4, -15(R14)(R15*1)          // 62137d4c3b8c3ef1ffffff01
	//TODO: VEXTRACTI32X8 $1, Z23, K4, -15(BX)                 // 62e37d4c3bbbf1ffffff01
	//TODO: VEXTRACTI32X8 $1, Z9, K4, -15(BX)                  // 62737d4c3b8bf1ffffff01
	//TODO: VEXTRACTI64X2 $0, Y9, K2, X21                      // 6233fd2a39cd00
	//TODO: VEXTRACTI64X2 $0, Y9, K2, -7(CX)                   // 6273fd2a3989f9ffffff00
	//TODO: VEXTRACTI64X2 $0, Y9, K2, 15(DX)(BX*4)             // 6273fd2a398c9a0f00000000
	//TODO: VEXTRACTI64X2 $2, Z27, K2, X1                      // 6263fd4a39d902
	//TODO: VEXTRACTI64X2 $2, Z14, K2, X1                      // 6273fd4a39f102
	//TODO: VEXTRACTI64X2 $2, Z27, K2, 99(R15)(R15*8)          // 6203fd4a399cff6300000002
	//TODO: VEXTRACTI64X2 $2, Z14, K2, 99(R15)(R15*8)          // 6213fd4a39b4ff6300000002
	//TODO: VEXTRACTI64X2 $2, Z27, K2, 7(AX)(CX*8)             // 6263fd4a399cc80700000002
	//TODO: VEXTRACTI64X2 $2, Z14, K2, 7(AX)(CX*8)             // 6273fd4a39b4c80700000002
	//TODO: VFPCLASSPDX $65, X6, K4, K1                        // 62f3fd0c66ce41
	//TODO: VFPCLASSPDX $65, (R14), K4, K1                     // 62d3fd0c660e41
	//TODO: VFPCLASSPDX $65, -7(DI)(R8*8), K4, K1              // 62b3fd0c668cc7f9ffffff41
	//TODO: VFPCLASSPDX $65, X6, K4, K3                        // 62f3fd0c66de41
	//TODO: VFPCLASSPDX $65, (R14), K4, K3                     // 62d3fd0c661e41
	//TODO: VFPCLASSPDX $65, -7(DI)(R8*8), K4, K3              // 62b3fd0c669cc7f9ffffff41
	//TODO: VFPCLASSPDY $67, Y7, K1, K6                        // 62f3fd2966f743
	//TODO: VFPCLASSPDY $67, 7(SI)(DI*8), K1, K6               // 62f3fd2966b4fe0700000043
	//TODO: VFPCLASSPDY $67, -15(R14), K1, K6                  // 62d3fd2966b6f1ffffff43
	//TODO: VFPCLASSPDY $67, Y7, K1, K7                        // 62f3fd2966ff43
	//TODO: VFPCLASSPDY $67, 7(SI)(DI*8), K1, K7               // 62f3fd2966bcfe0700000043
	//TODO: VFPCLASSPDY $67, -15(R14), K1, K7                  // 62d3fd2966bef1ffffff43
	//TODO: VFPCLASSPDZ $127, Z3, K3, K6                       // 62f3fd4b66f37f
	//TODO: VFPCLASSPDZ $127, Z27, K3, K6                      // 6293fd4b66f37f
	//TODO: VFPCLASSPDZ $127, 7(AX)(CX*4), K3, K6              // 62f3fd4b66b488070000007f
	//TODO: VFPCLASSPDZ $127, 7(AX)(CX*1), K3, K6              // 62f3fd4b66b408070000007f
	//TODO: VFPCLASSPDZ $127, Z3, K3, K4                       // 62f3fd4b66e37f
	//TODO: VFPCLASSPDZ $127, Z27, K3, K4                      // 6293fd4b66e37f
	//TODO: VFPCLASSPDZ $127, 7(AX)(CX*4), K3, K4              // 62f3fd4b66a488070000007f
	//TODO: VFPCLASSPDZ $127, 7(AX)(CX*1), K3, K4              // 62f3fd4b66a408070000007f
	//TODO: VFPCLASSPSX $0, X1, K4, K4                         // 62f37d0c66e100
	//TODO: VFPCLASSPSX $0, 99(R15)(R15*4), K4, K4             // 62937d0c66a4bf6300000000
	//TODO: VFPCLASSPSX $0, 15(DX), K4, K4                     // 62f37d0c66a20f00000000
	//TODO: VFPCLASSPSX $0, X1, K4, K6                         // 62f37d0c66f100
	//TODO: VFPCLASSPSX $0, 99(R15)(R15*4), K4, K6             // 62937d0c66b4bf6300000000
	//TODO: VFPCLASSPSX $0, 15(DX), K4, K6                     // 62f37d0c66b20f00000000
	//TODO: VFPCLASSPSY $97, Y0, K5, K4                        // 62f37d2d66e061
	//TODO: VFPCLASSPSY $97, 7(SI)(DI*1), K5, K4               // 62f37d2d66a43e0700000061
	//TODO: VFPCLASSPSY $97, 15(DX)(BX*8), K5, K4              // 62f37d2d66a4da0f00000061
	//TODO: VFPCLASSPSY $97, Y0, K5, K5                        // 62f37d2d66e861
	//TODO: VFPCLASSPSY $97, 7(SI)(DI*1), K5, K5               // 62f37d2d66ac3e0700000061
	//TODO: VFPCLASSPSY $97, 15(DX)(BX*8), K5, K5              // 62f37d2d66acda0f00000061
	//TODO: VFPCLASSPSZ $81, Z7, K7, K2                        // 62f37d4f66d751
	//TODO: VFPCLASSPSZ $81, Z9, K7, K2                        // 62d37d4f66d151
	//TODO: VFPCLASSPSZ $81, (SI), K7, K2                      // 62f37d4f661651
	//TODO: VFPCLASSPSZ $81, 7(SI)(DI*2), K7, K2               // 62f37d4f66947e0700000051
	//TODO: VFPCLASSPSZ $81, Z7, K7, K7                        // 62f37d4f66ff51
	//TODO: VFPCLASSPSZ $81, Z9, K7, K7                        // 62d37d4f66f951
	//TODO: VFPCLASSPSZ $81, (SI), K7, K7                      // 62f37d4f663e51
	//TODO: VFPCLASSPSZ $81, 7(SI)(DI*2), K7, K7               // 62f37d4f66bc7e0700000051
	//TODO: VFPCLASSSD $42, X8, K7, K0                         // 62d3fd0f67c02a or 62d3fd2f67c02a or 62d3fd4f67c02a
	//TODO: VFPCLASSSD $42, (BX), K7, K0                       // 62f3fd0f67032a or 62f3fd2f67032a or 62f3fd4f67032a
	//TODO: VFPCLASSSD $42, -17(BP)(SI*1), K7, K0              // 62f3fd0f678435efffffff2a or 62f3fd2f678435efffffff2a or 62f3fd4f678435efffffff2a
	//TODO: VFPCLASSSD $42, X8, K7, K5                         // 62d3fd0f67e82a or 62d3fd2f67e82a or 62d3fd4f67e82a
	//TODO: VFPCLASSSD $42, (BX), K7, K5                       // 62f3fd0f672b2a or 62f3fd2f672b2a or 62f3fd4f672b2a
	//TODO: VFPCLASSSD $42, -17(BP)(SI*1), K7, K5              // 62f3fd0f67ac35efffffff2a or 62f3fd2f67ac35efffffff2a or 62f3fd4f67ac35efffffff2a
	//TODO: VFPCLASSSS $79, X8, K6, K6                         // 62d37d0e67f04f or 62d37d2e67f04f or 62d37d4e67f04f
	//TODO: VFPCLASSSS $79, 7(SI)(DI*1), K6, K6                // 62f37d0e67b43e070000004f or 62f37d2e67b43e070000004f or 62f37d4e67b43e070000004f
	//TODO: VFPCLASSSS $79, 15(DX)(BX*8), K6, K6               // 62f37d0e67b4da0f0000004f or 62f37d2e67b4da0f0000004f or 62f37d4e67b4da0f0000004f
	//TODO: VFPCLASSSS $79, X8, K6, K5                         // 62d37d0e67e84f or 62d37d2e67e84f or 62d37d4e67e84f
	//TODO: VFPCLASSSS $79, 7(SI)(DI*1), K6, K5                // 62f37d0e67ac3e070000004f or 62f37d2e67ac3e070000004f or 62f37d4e67ac3e070000004f
	//TODO: VFPCLASSSS $79, 15(DX)(BX*8), K6, K5               // 62f37d0e67acda0f0000004f or 62f37d2e67acda0f0000004f or 62f37d4e67acda0f0000004f
	//TODO: VINSERTF32X8 $1, Y12, Z0, K2, Z23                  // 62c37d4a1afc01
	//TODO: VINSERTF32X8 $1, 17(SP)(BP*1), Z0, K2, Z23         // 62e37d4a1abc2c1100000001
	//TODO: VINSERTF32X8 $1, -7(CX)(DX*8), Z0, K2, Z23         // 62e37d4a1abcd1f9ffffff01
	//TODO: VINSERTF32X8 $1, Y12, Z11, K2, Z23                 // 62c3254a1afc01
	//TODO: VINSERTF32X8 $1, 17(SP)(BP*1), Z11, K2, Z23        // 62e3254a1abc2c1100000001
	//TODO: VINSERTF32X8 $1, -7(CX)(DX*8), Z11, K2, Z23        // 62e3254a1abcd1f9ffffff01
	//TODO: VINSERTF32X8 $1, Y12, Z0, K2, Z19                  // 62c37d4a1adc01
	//TODO: VINSERTF32X8 $1, 17(SP)(BP*1), Z0, K2, Z19         // 62e37d4a1a9c2c1100000001
	//TODO: VINSERTF32X8 $1, -7(CX)(DX*8), Z0, K2, Z19         // 62e37d4a1a9cd1f9ffffff01
	//TODO: VINSERTF32X8 $1, Y12, Z11, K2, Z19                 // 62c3254a1adc01
	//TODO: VINSERTF32X8 $1, 17(SP)(BP*1), Z11, K2, Z19        // 62e3254a1a9c2c1100000001
	//TODO: VINSERTF32X8 $1, -7(CX)(DX*8), Z11, K2, Z19        // 62e3254a1a9cd1f9ffffff01
	//TODO: VINSERTF64X2 $0, X19, Y14, K4, Y21                 // 62a38d2c18eb00
	//TODO: VINSERTF64X2 $0, 7(AX)(CX*4), Y14, K4, Y21         // 62e38d2c18ac880700000000
	//TODO: VINSERTF64X2 $0, 7(AX)(CX*1), Y14, K4, Y21         // 62e38d2c18ac080700000000
	//TODO: VINSERTF64X2 $1, X0, Z24, K1, Z0                   // 62f3bd4118c001
	//TODO: VINSERTF64X2 $1, (SI), Z24, K1, Z0                 // 62f3bd41180601
	//TODO: VINSERTF64X2 $1, 7(SI)(DI*2), Z24, K1, Z0          // 62f3bd4118847e0700000001
	//TODO: VINSERTF64X2 $1, X0, Z12, K1, Z0                   // 62f39d4918c001
	//TODO: VINSERTF64X2 $1, (SI), Z12, K1, Z0                 // 62f39d49180601
	//TODO: VINSERTF64X2 $1, 7(SI)(DI*2), Z12, K1, Z0          // 62f39d4918847e0700000001
	//TODO: VINSERTF64X2 $1, X0, Z24, K1, Z25                  // 6263bd4118c801
	//TODO: VINSERTF64X2 $1, (SI), Z24, K1, Z25                // 6263bd41180e01
	//TODO: VINSERTF64X2 $1, 7(SI)(DI*2), Z24, K1, Z25         // 6263bd41188c7e0700000001
	//TODO: VINSERTF64X2 $1, X0, Z12, K1, Z25                  // 62639d4918c801
	//TODO: VINSERTF64X2 $1, (SI), Z12, K1, Z25                // 62639d49180e01
	//TODO: VINSERTF64X2 $1, 7(SI)(DI*2), Z12, K1, Z25         // 62639d49188c7e0700000001
	//TODO: VINSERTI32X8 $1, Y16, Z17, K7, Z20                 // 62a375473ae001
	//TODO: VINSERTI32X8 $1, 15(R8)(R14*1), Z17, K7, Z20       // 628375473aa4300f00000001
	//TODO: VINSERTI32X8 $1, 15(R8)(R14*2), Z17, K7, Z20       // 628375473aa4700f00000001
	//TODO: VINSERTI32X8 $1, Y16, Z0, K7, Z20                  // 62a37d4f3ae001
	//TODO: VINSERTI32X8 $1, 15(R8)(R14*1), Z0, K7, Z20        // 62837d4f3aa4300f00000001
	//TODO: VINSERTI32X8 $1, 15(R8)(R14*2), Z0, K7, Z20        // 62837d4f3aa4700f00000001
	//TODO: VINSERTI32X8 $1, Y16, Z17, K7, Z0                  // 62b375473ac001
	//TODO: VINSERTI32X8 $1, 15(R8)(R14*1), Z17, K7, Z0        // 629375473a84300f00000001
	//TODO: VINSERTI32X8 $1, 15(R8)(R14*2), Z17, K7, Z0        // 629375473a84700f00000001
	//TODO: VINSERTI32X8 $1, Y16, Z0, K7, Z0                   // 62b37d4f3ac001
	//TODO: VINSERTI32X8 $1, 15(R8)(R14*1), Z0, K7, Z0         // 62937d4f3a84300f00000001
	//TODO: VINSERTI32X8 $1, 15(R8)(R14*2), Z0, K7, Z0         // 62937d4f3a84700f00000001
	//TODO: VINSERTI64X2 $0, X7, Y30, K7, Y1                   // 62f38d2738cf00
	//TODO: VINSERTI64X2 $0, 17(SP), Y30, K7, Y1               // 62f38d27388c241100000000
	//TODO: VINSERTI64X2 $0, -17(BP)(SI*4), Y30, K7, Y1        // 62f38d27388cb5efffffff00
	//TODO: VINSERTI64X2 $3, X8, Z31, K6, Z17                  // 62c3854638c803
	//TODO: VINSERTI64X2 $3, 7(AX), Z31, K6, Z17               // 62e3854638880700000003
	//TODO: VINSERTI64X2 $3, (DI), Z31, K6, Z17                // 62e38546380f03
	//TODO: VINSERTI64X2 $3, X8, Z0, K6, Z17                   // 62c3fd4e38c803
	//TODO: VINSERTI64X2 $3, 7(AX), Z0, K6, Z17                // 62e3fd4e38880700000003
	//TODO: VINSERTI64X2 $3, (DI), Z0, K6, Z17                 // 62e3fd4e380f03
	//TODO: VINSERTI64X2 $3, X8, Z31, K6, Z23                  // 62c3854638f803
	//TODO: VINSERTI64X2 $3, 7(AX), Z31, K6, Z23               // 62e3854638b80700000003
	//TODO: VINSERTI64X2 $3, (DI), Z31, K6, Z23                // 62e38546383f03
	//TODO: VINSERTI64X2 $3, X8, Z0, K6, Z23                   // 62c3fd4e38f803
	//TODO: VINSERTI64X2 $3, 7(AX), Z0, K6, Z23                // 62e3fd4e38b80700000003
	//TODO: VINSERTI64X2 $3, (DI), Z0, K6, Z23                 // 62e3fd4e383f03
	//TODO: VORPD X0, X6, K7, X8                               // 6271cd0f56c0
	//TODO: VORPD -17(BP)(SI*8), X6, K7, X8                    // 6271cd0f5684f5efffffff
	//TODO: VORPD (R15), X6, K7, X8                            // 6251cd0f5607
	//TODO: VORPD Y28, Y9, K1, Y20                             // 6281b52956e4
	//TODO: VORPD 99(R15)(R15*2), Y9, K1, Y20                  // 6281b52956a47f63000000
	//TODO: VORPD -7(DI), Y9, K1, Y20                          // 62e1b52956a7f9ffffff
	//TODO: VORPD Z9, Z9, K1, Z0                               // 62d1b54956c1
	//TODO: VORPD Z25, Z9, K1, Z0                              // 6291b54956c1
	//TODO: VORPD -7(CX), Z9, K1, Z0                           // 62f1b5495681f9ffffff
	//TODO: VORPD 15(DX)(BX*4), Z9, K1, Z0                     // 62f1b54956849a0f000000
	//TODO: VORPD Z9, Z3, K1, Z0                               // 62d1e54956c1
	//TODO: VORPD Z25, Z3, K1, Z0                              // 6291e54956c1
	//TODO: VORPD -7(CX), Z3, K1, Z0                           // 62f1e5495681f9ffffff
	//TODO: VORPD 15(DX)(BX*4), Z3, K1, Z0                     // 62f1e54956849a0f000000
	//TODO: VORPD Z9, Z9, K1, Z26                              // 6241b54956d1
	//TODO: VORPD Z25, Z9, K1, Z26                             // 6201b54956d1
	//TODO: VORPD -7(CX), Z9, K1, Z26                          // 6261b5495691f9ffffff
	//TODO: VORPD 15(DX)(BX*4), Z9, K1, Z26                    // 6261b54956949a0f000000
	//TODO: VORPD Z9, Z3, K1, Z26                              // 6241e54956d1
	//TODO: VORPD Z25, Z3, K1, Z26                             // 6201e54956d1
	//TODO: VORPD -7(CX), Z3, K1, Z26                          // 6261e5495691f9ffffff
	//TODO: VORPD 15(DX)(BX*4), Z3, K1, Z26                    // 6261e54956949a0f000000
	//TODO: VORPS X6, X16, K1, X11                             // 62717c0156de
	//TODO: VORPS 7(SI)(DI*8), X16, K1, X11                    // 62717c01569cfe07000000
	//TODO: VORPS -15(R14), X16, K1, X11                       // 62517c01569ef1ffffff
	//TODO: VORPS Y8, Y1, K7, Y28                              // 6241742f56e0
	//TODO: VORPS -7(CX)(DX*1), Y1, K7, Y28                    // 6261742f56a411f9ffffff
	//TODO: VORPS -15(R14)(R15*4), Y1, K7, Y28                 // 6201742f56a4bef1ffffff
	//TODO: VORPS Z17, Z20, K2, Z9                             // 62315c4256c9
	//TODO: VORPS Z0, Z20, K2, Z9                              // 62715c4256c8
	//TODO: VORPS 99(R15)(R15*8), Z20, K2, Z9                  // 62115c42568cff63000000
	//TODO: VORPS 7(AX)(CX*8), Z20, K2, Z9                     // 62715c42568cc807000000
	//TODO: VORPS Z17, Z0, K2, Z9                              // 62317c4a56c9
	//TODO: VORPS Z0, Z0, K2, Z9                               // 62717c4a56c8
	//TODO: VORPS 99(R15)(R15*8), Z0, K2, Z9                   // 62117c4a568cff63000000
	//TODO: VORPS 7(AX)(CX*8), Z0, K2, Z9                      // 62717c4a568cc807000000
	//TODO: VORPS Z17, Z20, K2, Z28                            // 62215c4256e1
	//TODO: VORPS Z0, Z20, K2, Z28                             // 62615c4256e0
	//TODO: VORPS 99(R15)(R15*8), Z20, K2, Z28                 // 62015c4256a4ff63000000
	//TODO: VORPS 7(AX)(CX*8), Z20, K2, Z28                    // 62615c4256a4c807000000
	//TODO: VORPS Z17, Z0, K2, Z28                             // 62217c4a56e1
	//TODO: VORPS Z0, Z0, K2, Z28                              // 62617c4a56e0
	//TODO: VORPS 99(R15)(R15*8), Z0, K2, Z28                  // 62017c4a56a4ff63000000
	//TODO: VORPS 7(AX)(CX*8), Z0, K2, Z28                     // 62617c4a56a4c807000000
	//TODO: VPEXTRD $64, X22, CX                               // 62e37d0816f140
	//TODO: VPEXTRD $64, X22, SP                               // 62e37d0816f440
	//TODO: VPEXTRD $64, X22, 99(R15)(R15*2)                   // 62837d0816b47f6300000040
	//TODO: VPEXTRD $64, X22, -7(DI)                           // 62e37d0816b7f9ffffff40
	//TODO: VPEXTRQ $27, X30, R9                               // 6243fd0816f11b
	//TODO: VPEXTRQ $27, X30, R13                              // 6243fd0816f51b
	//TODO: VPEXTRQ $27, X30, -15(R14)(R15*1)                  // 6203fd0816b43ef1ffffff1b
	//TODO: VPEXTRQ $27, X30, -15(BX)                          // 6263fd0816b3f1ffffff1b
	//TODO: VPINSRD $82, R9, X30, X23                          // 62c30d0022f952
	//TODO: VPINSRD $82, CX, X30, X23                          // 62e30d0022f952
	//TODO: VPINSRD $82, -7(CX)(DX*1), X30, X23                // 62e30d0022bc11f9ffffff52
	//TODO: VPINSRD $82, -15(R14)(R15*4), X30, X23             // 62830d0022bcbef1ffffff52
	//TODO: VPINSRQ $126, DX, X20, X8                          // 6273dd0022c27e
	//TODO: VPINSRQ $126, BP, X20, X8                          // 6273dd0022c57e
	//TODO: VPINSRQ $126, 7(AX)(CX*4), X20, X8                 // 6273dd00228488070000007e
	//TODO: VPINSRQ $126, 7(AX)(CX*1), X20, X8                 // 6273dd00228408070000007e
	//TODO: VPMOVD2M X30, K6                                   // 62927e0839f6
	//TODO: VPMOVD2M X30, K7                                   // 62927e0839fe
	//TODO: VPMOVD2M Y2, K6                                    // 62f27e2839f2
	//TODO: VPMOVD2M Y2, K4                                    // 62f27e2839e2
	//TODO: VPMOVD2M Z1, K4                                    // 62f27e4839e1
	//TODO: VPMOVD2M Z9, K4                                    // 62d27e4839e1
	//TODO: VPMOVD2M Z1, K6                                    // 62f27e4839f1
	//TODO: VPMOVD2M Z9, K6                                    // 62d27e4839f1
	//TODO: VPMOVM2D K6, X23                                   // 62e27e0838fe
	//TODO: VPMOVM2D K5, X23                                   // 62e27e0838fd
	//TODO: VPMOVM2D K1, Y9                                    // 62727e2838c9
	//TODO: VPMOVM2D K5, Y9                                    // 62727e2838cd
	//TODO: VPMOVM2D K3, Z7                                    // 62f27e4838fb
	//TODO: VPMOVM2D K1, Z7                                    // 62f27e4838f9
	//TODO: VPMOVM2D K3, Z21                                   // 62e27e4838eb
	//TODO: VPMOVM2D K1, Z21                                   // 62e27e4838e9
	//TODO: VPMOVM2Q K5, X12                                   // 6272fe0838e5
	//TODO: VPMOVM2Q K4, X12                                   // 6272fe0838e4
	//TODO: VPMOVM2Q K7, Y3                                    // 62f2fe2838df
	//TODO: VPMOVM2Q K6, Y3                                    // 62f2fe2838de
	//TODO: VPMOVM2Q K4, Z16                                   // 62e2fe4838c4
	//TODO: VPMOVM2Q K6, Z16                                   // 62e2fe4838c6
	//TODO: VPMOVM2Q K4, Z25                                   // 6262fe4838cc
	//TODO: VPMOVM2Q K6, Z25                                   // 6262fe4838ce
	//TODO: VPMOVQ2M X23, K1                                   // 62b2fe0839cf
	//TODO: VPMOVQ2M X23, K3                                   // 62b2fe0839df
	//TODO: VPMOVQ2M Y9, K6                                    // 62d2fe2839f1
	//TODO: VPMOVQ2M Y9, K7                                    // 62d2fe2839f9
	//TODO: VPMOVQ2M Z12, K6                                   // 62d2fe4839f4
	//TODO: VPMOVQ2M Z13, K6                                   // 62d2fe4839f5
	//TODO: VPMOVQ2M Z12, K4                                   // 62d2fe4839e4
	//TODO: VPMOVQ2M Z13, K4                                   // 62d2fe4839e5
	//TODO: VPMULLQ X0, X19, K7, X26                           // 6262e50740d0
	//TODO: VPMULLQ 15(R8)(R14*4), X19, K7, X26                // 6202e5074094b00f000000
	//TODO: VPMULLQ -7(CX)(DX*4), X19, K7, X26                 // 6262e507409491f9ffffff
	//TODO: VPMULLQ Y14, Y12, K2, Y26                          // 62429d2a40d6
	//TODO: VPMULLQ 15(DX)(BX*1), Y12, K2, Y26                 // 62629d2a40941a0f000000
	//TODO: VPMULLQ -7(CX)(DX*2), Y12, K2, Y26                 // 62629d2a409451f9ffffff
	//TODO: VPMULLQ Z3, Z20, K4, Z0                            // 62f2dd4440c3
	//TODO: VPMULLQ Z30, Z20, K4, Z0                           // 6292dd4440c6
	//TODO: VPMULLQ 15(R8)(R14*8), Z20, K4, Z0                 // 6292dd444084f00f000000
	//TODO: VPMULLQ -15(R14)(R15*2), Z20, K4, Z0               // 6292dd4440847ef1ffffff
	//TODO: VPMULLQ Z3, Z28, K4, Z0                            // 62f29d4440c3
	//TODO: VPMULLQ Z30, Z28, K4, Z0                           // 62929d4440c6
	//TODO: VPMULLQ 15(R8)(R14*8), Z28, K4, Z0                 // 62929d444084f00f000000
	//TODO: VPMULLQ -15(R14)(R15*2), Z28, K4, Z0               // 62929d4440847ef1ffffff
	//TODO: VPMULLQ Z3, Z20, K4, Z6                            // 62f2dd4440f3
	//TODO: VPMULLQ Z30, Z20, K4, Z6                           // 6292dd4440f6
	//TODO: VPMULLQ 15(R8)(R14*8), Z20, K4, Z6                 // 6292dd4440b4f00f000000
	//TODO: VPMULLQ -15(R14)(R15*2), Z20, K4, Z6               // 6292dd4440b47ef1ffffff
	//TODO: VPMULLQ Z3, Z28, K4, Z6                            // 62f29d4440f3
	//TODO: VPMULLQ Z30, Z28, K4, Z6                           // 62929d4440f6
	//TODO: VPMULLQ 15(R8)(R14*8), Z28, K4, Z6                 // 62929d4440b4f00f000000
	//TODO: VPMULLQ -15(R14)(R15*2), Z28, K4, Z6               // 62929d4440b47ef1ffffff
	//TODO: VRANGEPD $11, X24, X31, K2, X11                    // 6213850250d80b
	//TODO: VRANGEPD $11, 17(SP)(BP*8), X31, K2, X11           // 62738502509cec110000000b
	//TODO: VRANGEPD $11, 17(SP)(BP*4), X31, K2, X11           // 62738502509cac110000000b
	//TODO: VRANGEPD $12, Y0, Y9, K1, Y1                       // 62f3b52950c80c
	//TODO: VRANGEPD $12, (R8), Y9, K1, Y1                     // 62d3b52950080c
	//TODO: VRANGEPD $12, 15(DX)(BX*2), Y9, K1, Y1             // 62f3b529508c5a0f0000000c
	//TODO: VRANGEPD $13, Z21, Z12, K7, Z14                    // 62339d4f50f50d
	//TODO: VRANGEPD $13, Z9, Z12, K7, Z14                     // 62539d4f50f10d
	//TODO: VRANGEPD $13, Z21, Z13, K7, Z14                    // 6233954f50f50d
	//TODO: VRANGEPD $13, Z9, Z13, K7, Z14                     // 6253954f50f10d
	//TODO: VRANGEPD $13, Z21, Z12, K7, Z13                    // 62339d4f50ed0d
	//TODO: VRANGEPD $13, Z9, Z12, K7, Z13                     // 62539d4f50e90d
	//TODO: VRANGEPD $13, Z21, Z13, K7, Z13                    // 6233954f50ed0d
	//TODO: VRANGEPD $13, Z9, Z13, K7, Z13                     // 6253954f50e90d
	//TODO: VRANGEPD $14, Z23, Z27, K1, Z2                     // 62b3a54150d70e
	//TODO: VRANGEPD $14, Z9, Z27, K1, Z2                      // 62d3a54150d10e
	//TODO: VRANGEPD $14, (R14), Z27, K1, Z2                   // 62d3a54150160e
	//TODO: VRANGEPD $14, -7(DI)(R8*8), Z27, K1, Z2            // 62b3a5415094c7f9ffffff0e
	//TODO: VRANGEPD $14, Z23, Z25, K1, Z2                     // 62b3b54150d70e
	//TODO: VRANGEPD $14, Z9, Z25, K1, Z2                      // 62d3b54150d10e
	//TODO: VRANGEPD $14, (R14), Z25, K1, Z2                   // 62d3b54150160e
	//TODO: VRANGEPD $14, -7(DI)(R8*8), Z25, K1, Z2            // 62b3b5415094c7f9ffffff0e
	//TODO: VRANGEPD $14, Z23, Z27, K1, Z7                     // 62b3a54150ff0e
	//TODO: VRANGEPD $14, Z9, Z27, K1, Z7                      // 62d3a54150f90e
	//TODO: VRANGEPD $14, (R14), Z27, K1, Z7                   // 62d3a541503e0e
	//TODO: VRANGEPD $14, -7(DI)(R8*8), Z27, K1, Z7            // 62b3a54150bcc7f9ffffff0e
	//TODO: VRANGEPD $14, Z23, Z25, K1, Z7                     // 62b3b54150ff0e
	//TODO: VRANGEPD $14, Z9, Z25, K1, Z7                      // 62d3b54150f90e
	//TODO: VRANGEPD $14, (R14), Z25, K1, Z7                   // 62d3b541503e0e
	//TODO: VRANGEPD $14, -7(DI)(R8*8), Z25, K1, Z7            // 62b3b54150bcc7f9ffffff0e
	//TODO: VRANGEPS $15, X11, X0, K1, X14                     // 62537d0950f30f
	//TODO: VRANGEPS $15, 7(SI)(DI*4), X0, K1, X14             // 62737d0950b4be070000000f
	//TODO: VRANGEPS $15, -7(DI)(R8*2), X0, K1, X14            // 62337d0950b447f9ffffff0f
	//TODO: VRANGEPS $0, Y22, Y31, K1, Y19                     // 62a3052150de00
	//TODO: VRANGEPS $0, 17(SP)(BP*1), Y31, K1, Y19            // 62e30521509c2c1100000000
	//TODO: VRANGEPS $0, -7(CX)(DX*8), Y31, K1, Y19            // 62e30521509cd1f9ffffff00
	//TODO: VRANGEPS $1, Z14, Z3, K7, Z27                      // 6243654f50de01
	//TODO: VRANGEPS $1, Z7, Z3, K7, Z27                       // 6263654f50df01
	//TODO: VRANGEPS $1, Z14, Z0, K7, Z27                      // 62437d4f50de01
	//TODO: VRANGEPS $1, Z7, Z0, K7, Z27                       // 62637d4f50df01
	//TODO: VRANGEPS $1, Z14, Z3, K7, Z14                      // 6253654f50f601
	//TODO: VRANGEPS $1, Z7, Z3, K7, Z14                       // 6273654f50f701
	//TODO: VRANGEPS $1, Z14, Z0, K7, Z14                      // 62537d4f50f601
	//TODO: VRANGEPS $1, Z7, Z0, K7, Z14                       // 62737d4f50f701
	//TODO: VRANGEPS $2, Z1, Z22, K2, Z8                       // 62734d4250c102
	//TODO: VRANGEPS $2, Z16, Z22, K2, Z8                      // 62334d4250c002
	//TODO: VRANGEPS $2, 99(R15)(R15*4), Z22, K2, Z8           // 62134d425084bf6300000002
	//TODO: VRANGEPS $2, 15(DX), Z22, K2, Z8                   // 62734d4250820f00000002
	//TODO: VRANGEPS $2, Z1, Z25, K2, Z8                       // 6273354250c102
	//TODO: VRANGEPS $2, Z16, Z25, K2, Z8                      // 6233354250c002
	//TODO: VRANGEPS $2, 99(R15)(R15*4), Z25, K2, Z8           // 621335425084bf6300000002
	//TODO: VRANGEPS $2, 15(DX), Z25, K2, Z8                   // 6273354250820f00000002
	//TODO: VRANGEPS $2, Z1, Z22, K2, Z24                      // 62634d4250c102
	//TODO: VRANGEPS $2, Z16, Z22, K2, Z24                     // 62234d4250c002
	//TODO: VRANGEPS $2, 99(R15)(R15*4), Z22, K2, Z24          // 62034d425084bf6300000002
	//TODO: VRANGEPS $2, 15(DX), Z22, K2, Z24                  // 62634d4250820f00000002
	//TODO: VRANGEPS $2, Z1, Z25, K2, Z24                      // 6263354250c102
	//TODO: VRANGEPS $2, Z16, Z25, K2, Z24                     // 6223354250c002
	//TODO: VRANGEPS $2, 99(R15)(R15*4), Z25, K2, Z24          // 620335425084bf6300000002
	//TODO: VRANGEPS $2, 15(DX), Z25, K2, Z24                  // 6263354250820f00000002
	//TODO: VRANGESD $3, X20, X2, K4, X23                      // 62a3ed0c51fc03
	//TODO: VRANGESD $4, X0, X25, K1, X5                       // 62f3b50151e804 or 62f3b52151e804 or 62f3b54151e804
	//TODO: VRANGESD $4, 7(AX)(CX*4), X25, K1, X5              // 62f3b50151ac880700000004 or 62f3b52151ac880700000004 or 62f3b54151ac880700000004
	//TODO: VRANGESD $4, 7(AX)(CX*1), X25, K1, X5              // 62f3b50151ac080700000004 or 62f3b52151ac080700000004 or 62f3b54151ac080700000004
	//TODO: VRANGESS $5, X2, X13, K3, X9                       // 6273150b51ca05
	//TODO: VRANGESS $6, X2, X9, K4, X8                        // 6273350c51c206 or 6273352c51c206 or 6273354c51c206
	//TODO: VRANGESS $6, 7(SI)(DI*1), X9, K4, X8               // 6273350c51843e0700000006 or 6273352c51843e0700000006 or 6273354c51843e0700000006
	//TODO: VRANGESS $6, 15(DX)(BX*8), X9, K4, X8              // 6273350c5184da0f00000006 or 6273352c5184da0f00000006 or 6273354c5184da0f00000006
	//TODO: VREDUCEPD $126, X24, K3, X8                        // 6213fd0b56c07e
	//TODO: VREDUCEPD $126, 99(R15)(R15*1), K3, X8             // 6213fd0b56843f630000007e
	//TODO: VREDUCEPD $126, (DX), K3, X8                       // 6273fd0b56027e
	//TODO: VREDUCEPD $94, Y5, K3, Y0                          // 62f3fd2b56c55e
	//TODO: VREDUCEPD $94, (R14), K3, Y0                       // 62d3fd2b56065e
	//TODO: VREDUCEPD $94, -7(DI)(R8*8), K3, Y0                // 62b3fd2b5684c7f9ffffff5e
	//TODO: VREDUCEPD $121, Z3, K2, Z26                        // 6263fd4a56d379
	//TODO: VREDUCEPD $121, Z0, K2, Z26                        // 6263fd4a56d079
	//TODO: VREDUCEPD $121, Z3, K2, Z3                         // 62f3fd4a56db79
	//TODO: VREDUCEPD $121, Z0, K2, Z3                         // 62f3fd4a56d879
	//TODO: VREDUCEPD $13, Z11, K1, Z21                        // 62c3fd4956eb0d
	//TODO: VREDUCEPD $13, Z25, K1, Z21                        // 6283fd4956e90d
	//TODO: VREDUCEPD $13, -17(BP), K1, Z21                    // 62e3fd4956adefffffff0d
	//TODO: VREDUCEPD $13, -15(R14)(R15*8), K1, Z21            // 6283fd4956acfef1ffffff0d
	//TODO: VREDUCEPD $13, Z11, K1, Z13                        // 6253fd4956eb0d
	//TODO: VREDUCEPD $13, Z25, K1, Z13                        // 6213fd4956e90d
	//TODO: VREDUCEPD $13, -17(BP), K1, Z13                    // 6273fd4956adefffffff0d
	//TODO: VREDUCEPD $13, -15(R14)(R15*8), K1, Z13            // 6213fd4956acfef1ffffff0d
	//TODO: VREDUCEPS $65, X0, K2, X7                          // 62f37d0a56f841
	//TODO: VREDUCEPS $65, -17(BP)(SI*8), K2, X7               // 62f37d0a56bcf5efffffff41
	//TODO: VREDUCEPS $65, (R15), K2, X7                       // 62d37d0a563f41
	//TODO: VREDUCEPS $67, Y31, K1, Y19                        // 62837d2956df43
	//TODO: VREDUCEPS $67, 99(R15)(R15*4), K1, Y19             // 62837d29569cbf6300000043
	//TODO: VREDUCEPS $67, 15(DX), K1, Y19                     // 62e37d29569a0f00000043
	//TODO: VREDUCEPS $127, Z27, K7, Z3                        // 62937d4f56db7f
	//TODO: VREDUCEPS $127, Z15, K7, Z3                        // 62d37d4f56df7f
	//TODO: VREDUCEPS $127, Z27, K7, Z12                       // 62137d4f56e37f
	//TODO: VREDUCEPS $127, Z15, K7, Z12                       // 62537d4f56e77f
	//TODO: VREDUCEPS $0, Z23, K1, Z23                         // 62a37d4956ff00
	//TODO: VREDUCEPS $0, Z6, K1, Z23                          // 62e37d4956fe00
	//TODO: VREDUCEPS $0, 17(SP)(BP*2), K1, Z23                // 62e37d4956bc6c1100000000
	//TODO: VREDUCEPS $0, -7(DI)(R8*4), K1, Z23                // 62a37d4956bc87f9ffffff00
	//TODO: VREDUCEPS $0, Z23, K1, Z5                          // 62b37d4956ef00
	//TODO: VREDUCEPS $0, Z6, K1, Z5                           // 62f37d4956ee00
	//TODO: VREDUCEPS $0, 17(SP)(BP*2), K1, Z5                 // 62f37d4956ac6c1100000000
	//TODO: VREDUCEPS $0, -7(DI)(R8*4), K1, Z5                 // 62b37d4956ac87f9ffffff00
	//TODO: VREDUCESD $97, X11, X1, K1, X22                    // 62c3f50957f361
	//TODO: VREDUCESD $81, X8, X7, K1, X6                      // 62d3c50957f051 or 62d3c52957f051 or 62d3c54957f051
	//TODO: VREDUCESD $81, 7(SI)(DI*4), X7, K1, X6             // 62f3c50957b4be0700000051 or 62f3c52957b4be0700000051 or 62f3c54957b4be0700000051
	//TODO: VREDUCESD $81, -7(DI)(R8*2), X7, K1, X6            // 62b3c50957b447f9ffffff51 or 62b3c52957b447f9ffffff51 or 62b3c54957b447f9ffffff51
	//TODO: VREDUCESS $42, X28, X3, K7, X31                    // 6203650f57fc2a
	//TODO: VREDUCESS $79, X7, X24, K2, X20                    // 62e33d0257e74f or 62e33d2257e74f or 62e33d4257e74f
	//TODO: VREDUCESS $79, 99(R15)(R15*8), X24, K2, X20        // 62833d0257a4ff630000004f or 62833d2257a4ff630000004f or 62833d4257a4ff630000004f
	//TODO: VREDUCESS $79, 7(AX)(CX*8), X24, K2, X20           // 62e33d0257a4c8070000004f or 62e33d2257a4c8070000004f or 62e33d4257a4c8070000004f
	//TODO: VXORPD X16, X30, K5, X0                            // 62b18d0557c0
	//TODO: VXORPD -7(CX)(DX*1), X30, K5, X0                   // 62f18d05578411f9ffffff
	//TODO: VXORPD -15(R14)(R15*4), X30, K5, X0                // 62918d055784bef1ffffff
	//TODO: VXORPD Y2, Y7, K3, Y13                             // 6271c52b57ea
	//TODO: VXORPD -7(CX), Y7, K3, Y13                         // 6271c52b57a9f9ffffff
	//TODO: VXORPD 15(DX)(BX*4), Y7, K3, Y13                   // 6271c52b57ac9a0f000000
	//TODO: VXORPD Z13, Z28, K4, Z26                           // 62419d4457d5
	//TODO: VXORPD Z21, Z28, K4, Z26                           // 62219d4457d5
	//TODO: VXORPD 15(R8)(R14*1), Z28, K4, Z26                 // 62019d445794300f000000
	//TODO: VXORPD 15(R8)(R14*2), Z28, K4, Z26                 // 62019d445794700f000000
	//TODO: VXORPD Z13, Z6, K4, Z26                            // 6241cd4c57d5
	//TODO: VXORPD Z21, Z6, K4, Z26                            // 6221cd4c57d5
	//TODO: VXORPD 15(R8)(R14*1), Z6, K4, Z26                  // 6201cd4c5794300f000000
	//TODO: VXORPD 15(R8)(R14*2), Z6, K4, Z26                  // 6201cd4c5794700f000000
	//TODO: VXORPD Z13, Z28, K4, Z14                           // 62519d4457f5
	//TODO: VXORPD Z21, Z28, K4, Z14                           // 62319d4457f5
	//TODO: VXORPD 15(R8)(R14*1), Z28, K4, Z14                 // 62119d4457b4300f000000
	//TODO: VXORPD 15(R8)(R14*2), Z28, K4, Z14                 // 62119d4457b4700f000000
	//TODO: VXORPD Z13, Z6, K4, Z14                            // 6251cd4c57f5
	//TODO: VXORPD Z21, Z6, K4, Z14                            // 6231cd4c57f5
	//TODO: VXORPD 15(R8)(R14*1), Z6, K4, Z14                  // 6211cd4c57b4300f000000
	//TODO: VXORPD 15(R8)(R14*2), Z6, K4, Z14                  // 6211cd4c57b4700f000000
	//TODO: VXORPS X14, X11, K2, X14                           // 6251240a57f6
	//TODO: VXORPS 15(DX)(BX*1), X11, K2, X14                  // 6271240a57b41a0f000000
	//TODO: VXORPS -7(CX)(DX*2), X11, K2, X14                  // 6271240a57b451f9ffffff
	//TODO: VXORPS Y9, Y12, K2, Y21                            // 62c11c2a57e9
	//TODO: VXORPS 99(R15)(R15*8), Y12, K2, Y21                // 62811c2a57acff63000000
	//TODO: VXORPS 7(AX)(CX*8), Y12, K2, Y21                   // 62e11c2a57acc807000000
	//TODO: VXORPS Z21, Z3, K3, Z26                            // 6221644b57d5
	//TODO: VXORPS Z13, Z3, K3, Z26                            // 6241644b57d5
	//TODO: VXORPS (R14), Z3, K3, Z26                          // 6241644b5716
	//TODO: VXORPS -7(DI)(R8*8), Z3, K3, Z26                   // 6221644b5794c7f9ffffff
	//TODO: VXORPS Z21, Z0, K3, Z26                            // 62217c4b57d5
	//TODO: VXORPS Z13, Z0, K3, Z26                            // 62417c4b57d5
	//TODO: VXORPS (R14), Z0, K3, Z26                          // 62417c4b5716
	//TODO: VXORPS -7(DI)(R8*8), Z0, K3, Z26                   // 62217c4b5794c7f9ffffff
	//TODO: VXORPS Z21, Z3, K3, Z3                             // 62b1644b57dd
	//TODO: VXORPS Z13, Z3, K3, Z3                             // 62d1644b57dd
	//TODO: VXORPS (R14), Z3, K3, Z3                           // 62d1644b571e
	//TODO: VXORPS -7(DI)(R8*8), Z3, K3, Z3                    // 62b1644b579cc7f9ffffff
	//TODO: VXORPS Z21, Z0, K3, Z3                             // 62b17c4b57dd
	//TODO: VXORPS Z13, Z0, K3, Z3                             // 62d17c4b57dd
	//TODO: VXORPS (R14), Z0, K3, Z3                           // 62d17c4b571e
	//TODO: VXORPS -7(DI)(R8*8), Z0, K3, Z3                    // 62b17c4b579cc7f9ffffff
	RET
