// Code generated by avx512test. DO NOT EDIT.

#include "../../../../../../runtime/textflag.h"

TEXT asmtest_avx512_bitalg(SB), NOSPLIT, $0
	//TODO: VPOPCNTB X0, K4, X21                               // 62e27d0c54e8
	//TODO: VPOPCNTB 15(R8)(R14*1), K4, X21                    // 62827d0c54ac300f000000
	//TODO: VPOPCNTB 15(R8)(R14*2), K4, X21                    // 62827d0c54ac700f000000
	//TODO: VPOPCNTB Y20, K4, Y8                               // 62327d2c54c4
	//TODO: VPOPCNTB 15(R8)(R14*8), K4, Y8                     // 62127d2c5484f00f000000
	//TODO: VPOPCNTB -15(R14)(R15*2), K4, Y8                   // 62127d2c54847ef1ffffff
	//TODO: VPOPCNTB Z18, K7, Z13                              // 62327d4f54ea
	//TODO: VPOPCNTB Z8, K7, Z13                               // 62527d4f54e8
	//TODO: VPOPCNTB 17(SP)(BP*8), K7, Z13                     // 62727d4f54acec11000000
	//TODO: VPOPCNTB 17(SP)(BP*4), K7, Z13                     // 62727d4f54acac11000000
	//TODO: VPOPCNTW X16, K3, X7                               // 62b2fd0b54f8
	//TODO: VPOPCNTW (CX), K3, X7                              // 62f2fd0b5439
	//TODO: VPOPCNTW 99(R15), K3, X7                           // 62d2fd0b54bf63000000
	//TODO: VPOPCNTW Y20, K3, Y18                              // 62a2fd2b54d4
	//TODO: VPOPCNTW (SI), K3, Y18                             // 62e2fd2b5416
	//TODO: VPOPCNTW 7(SI)(DI*2), K3, Y18                      // 62e2fd2b54947e07000000
	//TODO: VPOPCNTW Z28, K3, Z12                              // 6212fd4b54e4
	//TODO: VPOPCNTW Z13, K3, Z12                              // 6252fd4b54e5
	//TODO: VPOPCNTW 7(AX), K3, Z12                            // 6272fd4b54a007000000
	//TODO: VPOPCNTW (DI), K3, Z12                             // 6272fd4b5427
	//TODO: VPOPCNTW Z28, K3, Z16                              // 6282fd4b54c4
	//TODO: VPOPCNTW Z13, K3, Z16                              // 62c2fd4b54c5
	//TODO: VPOPCNTW 7(AX), K3, Z16                            // 62e2fd4b548007000000
	//TODO: VPOPCNTW (DI), K3, Z16                             // 62e2fd4b5407
	//TODO: VPSHUFBITQMB X8, X2, K6, K0                        // 62d26d0e8fc0
	//TODO: VPSHUFBITQMB (R8), X2, K6, K0                      // 62d26d0e8f00
	//TODO: VPSHUFBITQMB 15(DX)(BX*2), X2, K6, K0              // 62f26d0e8f845a0f000000
	//TODO: VPSHUFBITQMB X8, X2, K6, K5                        // 62d26d0e8fe8
	//TODO: VPSHUFBITQMB (R8), X2, K6, K5                      // 62d26d0e8f28
	//TODO: VPSHUFBITQMB 15(DX)(BX*2), X2, K6, K5              // 62f26d0e8fac5a0f000000
	//TODO: VPSHUFBITQMB Y20, Y21, K3, K6                      // 62b255238ff4
	//TODO: VPSHUFBITQMB -17(BP), Y21, K3, K6                  // 62f255238fb5efffffff
	//TODO: VPSHUFBITQMB -15(R14)(R15*8), Y21, K3, K6          // 629255238fb4fef1ffffff
	//TODO: VPSHUFBITQMB Y20, Y21, K3, K5                      // 62b255238fec
	//TODO: VPSHUFBITQMB -17(BP), Y21, K3, K5                  // 62f255238fadefffffff
	//TODO: VPSHUFBITQMB -15(R14)(R15*8), Y21, K3, K5          // 629255238facfef1ffffff
	//TODO: VPSHUFBITQMB Z3, Z6, K7, K1                        // 62f24d4f8fcb
	//TODO: VPSHUFBITQMB Z21, Z6, K7, K1                       // 62b24d4f8fcd
	//TODO: VPSHUFBITQMB -15(R14)(R15*1), Z6, K7, K1           // 62924d4f8f8c3ef1ffffff
	//TODO: VPSHUFBITQMB -15(BX), Z6, K7, K1                   // 62f24d4f8f8bf1ffffff
	//TODO: VPSHUFBITQMB Z3, Z25, K7, K1                       // 62f235478fcb
	//TODO: VPSHUFBITQMB Z21, Z25, K7, K1                      // 62b235478fcd
	//TODO: VPSHUFBITQMB -15(R14)(R15*1), Z25, K7, K1          // 629235478f8c3ef1ffffff
	//TODO: VPSHUFBITQMB -15(BX), Z25, K7, K1                  // 62f235478f8bf1ffffff
	//TODO: VPSHUFBITQMB Z3, Z6, K7, K5                        // 62f24d4f8feb
	//TODO: VPSHUFBITQMB Z21, Z6, K7, K5                       // 62b24d4f8fed
	//TODO: VPSHUFBITQMB -15(R14)(R15*1), Z6, K7, K5           // 62924d4f8fac3ef1ffffff
	//TODO: VPSHUFBITQMB -15(BX), Z6, K7, K5                   // 62f24d4f8fabf1ffffff
	//TODO: VPSHUFBITQMB Z3, Z25, K7, K5                       // 62f235478feb
	//TODO: VPSHUFBITQMB Z21, Z25, K7, K5                      // 62b235478fed
	//TODO: VPSHUFBITQMB -15(R14)(R15*1), Z25, K7, K5          // 629235478fac3ef1ffffff
	//TODO: VPSHUFBITQMB -15(BX), Z25, K7, K5                  // 62f235478fabf1ffffff
	RET
