// Code generated by avx512test. DO NOT EDIT.

#include "../../../../../../runtime/textflag.h"

TEXT asmtest_avx512_vbmi2(SB), NOSPLIT, $0
	//TODO: VPCOMPRESSB X2, K1, X13                            // 62d27d0963d5
	//TODO: VPCOMPRESSB X2, K1, -7(CX)(DX*1)                   // 62f27d09635411f9
	//TODO: VPCOMPRESSB X2, K1, -15(R14)(R15*4)                // 62927d096354bef1
	//TODO: VPCOMPRESSB Y28, K1, Y0                            // 62627d2963e0
	//TODO: VPCOMPRESSB Y28, K1, -17(BP)(SI*8)                 // 62627d296364f5ef
	//TODO: VPCOMPRESSB Y28, K1, (R15)                         // 62427d296327
	//TODO: VPCOMPRESSB Z2, K1, Z5                             // 62f27d4963d5
	//TODO: VPCOMPRESSB Z2, K1, Z23                            // 62b27d4963d7
	//TODO: VPCOMPRESSB Z2, K1, -17(BP)                        // 62f27d496355ef
	//TODO: VPCOMPRESSB Z2, K1, -15(R14)(R15*8)                // 62927d496354fef1
	//TODO: VPCOMPRESSW X22, K5, X11                           // 62c2fd0d63f3
	//TODO: VPCOMPRESSW X22, K5, 17(SP)(BP*2)                  // 62e2fd0d63b46c11000000
	//TODO: VPCOMPRESSW X22, K5, -7(DI)(R8*4)                  // 62a2fd0d63b487f9ffffff
	//TODO: VPCOMPRESSW Y14, K7, Y20                           // 6232fd2f63f4
	//TODO: VPCOMPRESSW Y14, K7, -7(DI)(R8*1)                  // 6232fd2f63b407f9ffffff
	//TODO: VPCOMPRESSW Y14, K7, (SP)                          // 6272fd2f633424
	//TODO: VPCOMPRESSW Z3, K7, Z26                            // 6292fd4f63da
	//TODO: VPCOMPRESSW Z0, K7, Z26                            // 6292fd4f63c2
	//TODO: VPCOMPRESSW Z3, K7, Z3                             // 62f2fd4f63db
	//TODO: VPCOMPRESSW Z0, K7, Z3                             // 62f2fd4f63c3
	//TODO: VPCOMPRESSW Z3, K7, 15(R8)(R14*8)                  // 6292fd4f639cf00f000000
	//TODO: VPCOMPRESSW Z0, K7, 15(R8)(R14*8)                  // 6292fd4f6384f00f000000
	//TODO: VPCOMPRESSW Z3, K7, -15(R14)(R15*2)                // 6292fd4f639c7ef1ffffff
	//TODO: VPCOMPRESSW Z0, K7, -15(R14)(R15*2)                // 6292fd4f63847ef1ffffff
	//TODO: VPEXPANDB X11, K1, X18                             // 62c27d0962d3
	//TODO: VPEXPANDB 99(R15)(R15*4), K1, X18                  // 62827d096254bf63
	//TODO: VPEXPANDB 15(DX), K1, X18                          // 62e27d0962520f
	//TODO: VPEXPANDB Y1, K1, Y14                              // 62727d2962f1
	//TODO: VPEXPANDB -7(DI)(R8*1), K1, Y14                    // 62327d29627407f9
	//TODO: VPEXPANDB (SP), K1, Y14                            // 62727d29623424
	//TODO: VPEXPANDB Z14, K1, Z15                             // 62527d4962fe
	//TODO: VPEXPANDB Z27, K1, Z15                             // 62127d4962fb
	//TODO: VPEXPANDB 15(R8)(R14*8), K1, Z15                   // 62127d49627cf00f
	//TODO: VPEXPANDB -15(R14)(R15*2), K1, Z15                 // 62127d49627c7ef1
	//TODO: VPEXPANDB Z14, K1, Z12                             // 62527d4962e6
	//TODO: VPEXPANDB Z27, K1, Z12                             // 62127d4962e3
	//TODO: VPEXPANDB 15(R8)(R14*8), K1, Z12                   // 62127d496264f00f
	//TODO: VPEXPANDB -15(R14)(R15*2), K1, Z12                 // 62127d4962647ef1
	//TODO: VPEXPANDW X27, K5, X2                              // 6292fd0d62d3
	//TODO: VPEXPANDW -7(CX)(DX*1), K5, X2                     // 62f2fd0d629411f9ffffff
	//TODO: VPEXPANDW -15(R14)(R15*4), K5, X2                  // 6292fd0d6294bef1ffffff
	//TODO: VPEXPANDW Y31, K7, Y19                             // 6282fd2f62df
	//TODO: VPEXPANDW (AX), K7, Y19                            // 62e2fd2f6218
	//TODO: VPEXPANDW 7(SI), K7, Y19                           // 62e2fd2f629e07000000
	//TODO: VPEXPANDW Z26, K7, Z6                              // 6292fd4f62f2
	//TODO: VPEXPANDW Z14, K7, Z6                              // 62d2fd4f62f6
	//TODO: VPEXPANDW (SI), K7, Z6                             // 62f2fd4f6236
	//TODO: VPEXPANDW 7(SI)(DI*2), K7, Z6                      // 62f2fd4f62b47e07000000
	//TODO: VPEXPANDW Z26, K7, Z14                             // 6212fd4f62f2
	//TODO: VPEXPANDW Z14, K7, Z14                             // 6252fd4f62f6
	//TODO: VPEXPANDW (SI), K7, Z14                            // 6272fd4f6236
	//TODO: VPEXPANDW 7(SI)(DI*2), K7, Z14                     // 6272fd4f62b47e07000000
	//TODO: VPSHLDD $47, X14, X7, K4, X9                       // 6253450c71ce2f
	//TODO: VPSHLDD $47, 7(SI)(DI*4), X7, K4, X9               // 6273450c718cbe070000002f
	//TODO: VPSHLDD $47, -7(DI)(R8*2), X7, K4, X9              // 6233450c718c47f9ffffff2f
	//TODO: VPSHLDD $82, Y31, Y19, K1, Y0                      // 6293652171c752
	//TODO: VPSHLDD $82, (AX), Y19, K1, Y0                     // 62f36521710052
	//TODO: VPSHLDD $82, 7(SI), Y19, K1, Y0                    // 62f3652171860700000052
	//TODO: VPSHLDD $126, Z27, Z2, K3, Z21                     // 62836d4b71eb7e
	//TODO: VPSHLDD $126, Z25, Z2, K3, Z21                     // 62836d4b71e97e
	//TODO: VPSHLDD $126, 17(SP)(BP*1), Z2, K3, Z21            // 62e36d4b71ac2c110000007e
	//TODO: VPSHLDD $126, -7(CX)(DX*8), Z2, K3, Z21            // 62e36d4b71acd1f9ffffff7e
	//TODO: VPSHLDD $126, Z27, Z7, K3, Z21                     // 6283454b71eb7e
	//TODO: VPSHLDD $126, Z25, Z7, K3, Z21                     // 6283454b71e97e
	//TODO: VPSHLDD $126, 17(SP)(BP*1), Z7, K3, Z21            // 62e3454b71ac2c110000007e
	//TODO: VPSHLDD $126, -7(CX)(DX*8), Z7, K3, Z21            // 62e3454b71acd1f9ffffff7e
	//TODO: VPSHLDD $126, Z27, Z2, K3, Z9                      // 62136d4b71cb7e
	//TODO: VPSHLDD $126, Z25, Z2, K3, Z9                      // 62136d4b71c97e
	//TODO: VPSHLDD $126, 17(SP)(BP*1), Z2, K3, Z9             // 62736d4b718c2c110000007e
	//TODO: VPSHLDD $126, -7(CX)(DX*8), Z2, K3, Z9             // 62736d4b718cd1f9ffffff7e
	//TODO: VPSHLDD $126, Z27, Z7, K3, Z9                      // 6213454b71cb7e
	//TODO: VPSHLDD $126, Z25, Z7, K3, Z9                      // 6213454b71c97e
	//TODO: VPSHLDD $126, 17(SP)(BP*1), Z7, K3, Z9             // 6273454b718c2c110000007e
	//TODO: VPSHLDD $126, -7(CX)(DX*8), Z7, K3, Z9             // 6273454b718cd1f9ffffff7e
	//TODO: VPSHLDQ $94, X3, X31, K4, X5                       // 62f3850471eb5e
	//TODO: VPSHLDQ $94, 17(SP), X31, K4, X5                   // 62f3850471ac24110000005e
	//TODO: VPSHLDQ $94, -17(BP)(SI*4), X31, K4, X5            // 62f3850471acb5efffffff5e
	//TODO: VPSHLDQ $121, Y23, Y9, K5, Y22                     // 62a3b52d71f779
	//TODO: VPSHLDQ $121, (BX), Y9, K5, Y22                    // 62e3b52d713379
	//TODO: VPSHLDQ $121, -17(BP)(SI*1), Y9, K5, Y22           // 62e3b52d71b435efffffff79
	//TODO: VPSHLDQ $13, Z3, Z27, K7, Z23                      // 62e3a54771fb0d
	//TODO: VPSHLDQ $13, Z0, Z27, K7, Z23                      // 62e3a54771f80d
	//TODO: VPSHLDQ $13, -17(BP)(SI*2), Z27, K7, Z23           // 62e3a54771bc75efffffff0d
	//TODO: VPSHLDQ $13, 7(AX)(CX*2), Z27, K7, Z23             // 62e3a54771bc48070000000d
	//TODO: VPSHLDQ $13, Z3, Z14, K7, Z23                      // 62e38d4f71fb0d
	//TODO: VPSHLDQ $13, Z0, Z14, K7, Z23                      // 62e38d4f71f80d
	//TODO: VPSHLDQ $13, -17(BP)(SI*2), Z14, K7, Z23           // 62e38d4f71bc75efffffff0d
	//TODO: VPSHLDQ $13, 7(AX)(CX*2), Z14, K7, Z23             // 62e38d4f71bc48070000000d
	//TODO: VPSHLDQ $13, Z3, Z27, K7, Z9                       // 6273a54771cb0d
	//TODO: VPSHLDQ $13, Z0, Z27, K7, Z9                       // 6273a54771c80d
	//TODO: VPSHLDQ $13, -17(BP)(SI*2), Z27, K7, Z9            // 6273a547718c75efffffff0d
	//TODO: VPSHLDQ $13, 7(AX)(CX*2), Z27, K7, Z9              // 6273a547718c48070000000d
	//TODO: VPSHLDQ $13, Z3, Z14, K7, Z9                       // 62738d4f71cb0d
	//TODO: VPSHLDQ $13, Z0, Z14, K7, Z9                       // 62738d4f71c80d
	//TODO: VPSHLDQ $13, -17(BP)(SI*2), Z14, K7, Z9            // 62738d4f718c75efffffff0d
	//TODO: VPSHLDQ $13, 7(AX)(CX*2), Z14, K7, Z9              // 62738d4f718c48070000000d
	//TODO: VPSHLDVD X11, X1, K7, X21                          // 62c2750f71eb
	//TODO: VPSHLDVD 7(AX), X1, K7, X21                        // 62e2750f71a807000000
	//TODO: VPSHLDVD (DI), X1, K7, X21                         // 62e2750f712f
	//TODO: VPSHLDVD Y0, Y5, K6, Y31                           // 6262552e71f8
	//TODO: VPSHLDVD 15(R8)(R14*4), Y5, K6, Y31                // 6202552e71bcb00f000000
	//TODO: VPSHLDVD -7(CX)(DX*4), Y5, K6, Y31                 // 6262552e71bc91f9ffffff
	//TODO: VPSHLDVD Z22, Z8, K3, Z14                          // 62323d4b71f6
	//TODO: VPSHLDVD Z25, Z8, K3, Z14                          // 62123d4b71f1
	//TODO: VPSHLDVD 15(R8)(R14*1), Z8, K3, Z14                // 62123d4b71b4300f000000
	//TODO: VPSHLDVD 15(R8)(R14*2), Z8, K3, Z14                // 62123d4b71b4700f000000
	//TODO: VPSHLDVD Z22, Z24, K3, Z14                         // 62323d4371f6
	//TODO: VPSHLDVD Z25, Z24, K3, Z14                         // 62123d4371f1
	//TODO: VPSHLDVD 15(R8)(R14*1), Z24, K3, Z14               // 62123d4371b4300f000000
	//TODO: VPSHLDVD 15(R8)(R14*2), Z24, K3, Z14               // 62123d4371b4700f000000
	//TODO: VPSHLDVD Z22, Z8, K3, Z7                           // 62b23d4b71fe
	//TODO: VPSHLDVD Z25, Z8, K3, Z7                           // 62923d4b71f9
	//TODO: VPSHLDVD 15(R8)(R14*1), Z8, K3, Z7                 // 62923d4b71bc300f000000
	//TODO: VPSHLDVD 15(R8)(R14*2), Z8, K3, Z7                 // 62923d4b71bc700f000000
	//TODO: VPSHLDVD Z22, Z24, K3, Z7                          // 62b23d4371fe
	//TODO: VPSHLDVD Z25, Z24, K3, Z7                          // 62923d4371f9
	//TODO: VPSHLDVD 15(R8)(R14*1), Z24, K3, Z7                // 62923d4371bc300f000000
	//TODO: VPSHLDVD 15(R8)(R14*2), Z24, K3, Z7                // 62923d4371bc700f000000
	//TODO: VPSHLDVQ X30, X0, K7, X13                          // 6212fd0f71ee
	//TODO: VPSHLDVQ 99(R15)(R15*1), X0, K7, X13               // 6212fd0f71ac3f63000000
	//TODO: VPSHLDVQ (DX), X0, K7, X13                         // 6272fd0f712a
	//TODO: VPSHLDVQ Y31, Y19, K4, Y5                          // 6292e52471ef
	//TODO: VPSHLDVQ (R8), Y19, K4, Y5                         // 62d2e5247128
	//TODO: VPSHLDVQ 15(DX)(BX*2), Y19, K4, Y5                 // 62f2e52471ac5a0f000000
	//TODO: VPSHLDVQ Z0, Z6, K4, Z1                            // 62f2cd4c71c8
	//TODO: VPSHLDVQ Z8, Z6, K4, Z1                            // 62d2cd4c71c8
	//TODO: VPSHLDVQ (R14), Z6, K4, Z1                         // 62d2cd4c710e
	//TODO: VPSHLDVQ -7(DI)(R8*8), Z6, K4, Z1                  // 62b2cd4c718cc7f9ffffff
	//TODO: VPSHLDVQ Z0, Z2, K4, Z1                            // 62f2ed4c71c8
	//TODO: VPSHLDVQ Z8, Z2, K4, Z1                            // 62d2ed4c71c8
	//TODO: VPSHLDVQ (R14), Z2, K4, Z1                         // 62d2ed4c710e
	//TODO: VPSHLDVQ -7(DI)(R8*8), Z2, K4, Z1                  // 62b2ed4c718cc7f9ffffff
	//TODO: VPSHLDVQ Z0, Z6, K4, Z16                           // 62e2cd4c71c0
	//TODO: VPSHLDVQ Z8, Z6, K4, Z16                           // 62c2cd4c71c0
	//TODO: VPSHLDVQ (R14), Z6, K4, Z16                        // 62c2cd4c7106
	//TODO: VPSHLDVQ -7(DI)(R8*8), Z6, K4, Z16                 // 62a2cd4c7184c7f9ffffff
	//TODO: VPSHLDVQ Z0, Z2, K4, Z16                           // 62e2ed4c71c0
	//TODO: VPSHLDVQ Z8, Z2, K4, Z16                           // 62c2ed4c71c0
	//TODO: VPSHLDVQ (R14), Z2, K4, Z16                        // 62c2ed4c7106
	//TODO: VPSHLDVQ -7(DI)(R8*8), Z2, K4, Z16                 // 62a2ed4c7184c7f9ffffff
	//TODO: VPSHLDVW X11, X14, K7, X16                         // 62c28d0f70c3
	//TODO: VPSHLDVW -17(BP)(SI*8), X14, K7, X16               // 62e28d0f7084f5efffffff
	//TODO: VPSHLDVW (R15), X14, K7, X16                       // 62c28d0f7007
	//TODO: VPSHLDVW Y24, Y2, K2, Y28                          // 6202ed2a70e0
	//TODO: VPSHLDVW 17(SP)(BP*1), Y2, K2, Y28                 // 6262ed2a70a42c11000000
	//TODO: VPSHLDVW -7(CX)(DX*8), Y2, K2, Y28                 // 6262ed2a70a4d1f9ffffff
	//TODO: VPSHLDVW Z11, Z14, K5, Z15                         // 62528d4d70fb
	//TODO: VPSHLDVW Z5, Z14, K5, Z15                          // 62728d4d70fd
	//TODO: VPSHLDVW 99(R15)(R15*4), Z14, K5, Z15              // 62128d4d70bcbf63000000
	//TODO: VPSHLDVW 15(DX), Z14, K5, Z15                      // 62728d4d70ba0f000000
	//TODO: VPSHLDVW Z11, Z27, K5, Z15                         // 6252a54570fb
	//TODO: VPSHLDVW Z5, Z27, K5, Z15                          // 6272a54570fd
	//TODO: VPSHLDVW 99(R15)(R15*4), Z27, K5, Z15              // 6212a54570bcbf63000000
	//TODO: VPSHLDVW 15(DX), Z27, K5, Z15                      // 6272a54570ba0f000000
	//TODO: VPSHLDVW Z11, Z14, K5, Z12                         // 62528d4d70e3
	//TODO: VPSHLDVW Z5, Z14, K5, Z12                          // 62728d4d70e5
	//TODO: VPSHLDVW 99(R15)(R15*4), Z14, K5, Z12              // 62128d4d70a4bf63000000
	//TODO: VPSHLDVW 15(DX), Z14, K5, Z12                      // 62728d4d70a20f000000
	//TODO: VPSHLDVW Z11, Z27, K5, Z12                         // 6252a54570e3
	//TODO: VPSHLDVW Z5, Z27, K5, Z12                          // 6272a54570e5
	//TODO: VPSHLDVW 99(R15)(R15*4), Z27, K5, Z12              // 6212a54570a4bf63000000
	//TODO: VPSHLDVW 15(DX), Z27, K5, Z12                      // 6272a54570a20f000000
	//TODO: VPSHLDW $65, X8, X19, K3, X14                      // 6253e50370f041
	//TODO: VPSHLDW $65, 7(SI)(DI*8), X19, K3, X14             // 6273e50370b4fe0700000041
	//TODO: VPSHLDW $65, -15(R14), X19, K3, X14                // 6253e50370b6f1ffffff41
	//TODO: VPSHLDW $67, Y11, Y0, K4, Y27                      // 6243fd2c70db43
	//TODO: VPSHLDW $67, -17(BP)(SI*2), Y0, K4, Y27            // 6263fd2c709c75efffffff43
	//TODO: VPSHLDW $67, 7(AX)(CX*2), Y0, K4, Y27              // 6263fd2c709c480700000043
	//TODO: VPSHLDW $127, Z2, Z5, K2, Z13                      // 6273d54a70ea7f
	//TODO: VPSHLDW $127, (CX), Z5, K2, Z13                    // 6273d54a70297f
	//TODO: VPSHLDW $127, 99(R15), Z5, K2, Z13                 // 6253d54a70af630000007f
	//TODO: VPSHLDW $127, Z2, Z23, K2, Z13                     // 6273c54270ea7f
	//TODO: VPSHLDW $127, (CX), Z23, K2, Z13                   // 6273c54270297f
	//TODO: VPSHLDW $127, 99(R15), Z23, K2, Z13                // 6253c54270af630000007f
	//TODO: VPSHLDW $127, Z2, Z5, K2, Z14                      // 6273d54a70f27f
	//TODO: VPSHLDW $127, (CX), Z5, K2, Z14                    // 6273d54a70317f
	//TODO: VPSHLDW $127, 99(R15), Z5, K2, Z14                 // 6253d54a70b7630000007f
	//TODO: VPSHLDW $127, Z2, Z23, K2, Z14                     // 6273c54270f27f
	//TODO: VPSHLDW $127, (CX), Z23, K2, Z14                   // 6273c54270317f
	//TODO: VPSHLDW $127, 99(R15), Z23, K2, Z14                // 6253c54270b7630000007f
	//TODO: VPSHRDD $0, X23, X26, K2, X8                       // 62332d0273c700
	//TODO: VPSHRDD $0, 7(SI)(DI*1), X26, K2, X8               // 62732d0273843e0700000000
	//TODO: VPSHRDD $0, 15(DX)(BX*8), X26, K2, X8              // 62732d027384da0f00000000
	//TODO: VPSHRDD $97, Y14, Y3, K3, Y31                      // 6243652b73fe61
	//TODO: VPSHRDD $97, 15(R8)(R14*1), Y3, K3, Y31            // 6203652b73bc300f00000061
	//TODO: VPSHRDD $97, 15(R8)(R14*2), Y3, K3, Y31            // 6203652b73bc700f00000061
	//TODO: VPSHRDD $81, Z28, Z26, K3, Z6                      // 62932d4373f451
	//TODO: VPSHRDD $81, Z6, Z26, K3, Z6                       // 62f32d4373f651
	//TODO: VPSHRDD $81, 99(R15)(R15*2), Z26, K3, Z6           // 62932d4373b47f6300000051
	//TODO: VPSHRDD $81, -7(DI), Z26, K3, Z6                   // 62f32d4373b7f9ffffff51
	//TODO: VPSHRDD $81, Z28, Z14, K3, Z6                      // 62930d4b73f451
	//TODO: VPSHRDD $81, Z6, Z14, K3, Z6                       // 62f30d4b73f651
	//TODO: VPSHRDD $81, 99(R15)(R15*2), Z14, K3, Z6           // 62930d4b73b47f6300000051
	//TODO: VPSHRDD $81, -7(DI), Z14, K3, Z6                   // 62f30d4b73b7f9ffffff51
	//TODO: VPSHRDD $81, Z28, Z26, K3, Z14                     // 62132d4373f451
	//TODO: VPSHRDD $81, Z6, Z26, K3, Z14                      // 62732d4373f651
	//TODO: VPSHRDD $81, 99(R15)(R15*2), Z26, K3, Z14          // 62132d4373b47f6300000051
	//TODO: VPSHRDD $81, -7(DI), Z26, K3, Z14                  // 62732d4373b7f9ffffff51
	//TODO: VPSHRDD $81, Z28, Z14, K3, Z14                     // 62130d4b73f451
	//TODO: VPSHRDD $81, Z6, Z14, K3, Z14                      // 62730d4b73f651
	//TODO: VPSHRDD $81, 99(R15)(R15*2), Z14, K3, Z14          // 62130d4b73b47f6300000051
	//TODO: VPSHRDD $81, -7(DI), Z14, K3, Z14                  // 62730d4b73b7f9ffffff51
	//TODO: VPSHRDQ $42, X23, X16, K3, X12                     // 6233fd0373e72a
	//TODO: VPSHRDQ $42, -7(DI)(R8*1), X16, K3, X12            // 6233fd0373a407f9ffffff2a
	//TODO: VPSHRDQ $42, (SP), X16, K3, X12                    // 6273fd037324242a
	//TODO: VPSHRDQ $79, Y27, Y13, K2, Y2                      // 6293952a73d34f
	//TODO: VPSHRDQ $79, (R14), Y13, K2, Y2                    // 62d3952a73164f
	//TODO: VPSHRDQ $79, -7(DI)(R8*8), Y13, K2, Y2             // 62b3952a7394c7f9ffffff4f
	//TODO: VPSHRDQ $64, Z3, Z26, K1, Z13                      // 6273ad4173eb40
	//TODO: VPSHRDQ $64, Z0, Z26, K1, Z13                      // 6273ad4173e840
	//TODO: VPSHRDQ $64, -7(CX)(DX*1), Z26, K1, Z13            // 6273ad4173ac11f9ffffff40
	//TODO: VPSHRDQ $64, -15(R14)(R15*4), Z26, K1, Z13         // 6213ad4173acbef1ffffff40
	//TODO: VPSHRDQ $64, Z3, Z3, K1, Z13                       // 6273e54973eb40
	//TODO: VPSHRDQ $64, Z0, Z3, K1, Z13                       // 6273e54973e840
	//TODO: VPSHRDQ $64, -7(CX)(DX*1), Z3, K1, Z13             // 6273e54973ac11f9ffffff40
	//TODO: VPSHRDQ $64, -15(R14)(R15*4), Z3, K1, Z13          // 6213e54973acbef1ffffff40
	//TODO: VPSHRDQ $64, Z3, Z26, K1, Z21                      // 62e3ad4173eb40
	//TODO: VPSHRDQ $64, Z0, Z26, K1, Z21                      // 62e3ad4173e840
	//TODO: VPSHRDQ $64, -7(CX)(DX*1), Z26, K1, Z21            // 62e3ad4173ac11f9ffffff40
	//TODO: VPSHRDQ $64, -15(R14)(R15*4), Z26, K1, Z21         // 6283ad4173acbef1ffffff40
	//TODO: VPSHRDQ $64, Z3, Z3, K1, Z21                       // 62e3e54973eb40
	//TODO: VPSHRDQ $64, Z0, Z3, K1, Z21                       // 62e3e54973e840
	//TODO: VPSHRDQ $64, -7(CX)(DX*1), Z3, K1, Z21             // 62e3e54973ac11f9ffffff40
	//TODO: VPSHRDQ $64, -15(R14)(R15*4), Z3, K1, Z21          // 6283e54973acbef1ffffff40
	//TODO: VPSHRDVD X31, X11, K2, X23                         // 6282250a73ff
	//TODO: VPSHRDVD -7(CX), X11, K2, X23                      // 62e2250a73b9f9ffffff
	//TODO: VPSHRDVD 15(DX)(BX*4), X11, K2, X23                // 62e2250a73bc9a0f000000
	//TODO: VPSHRDVD Y20, Y22, K1, Y15                         // 62324d2173fc
	//TODO: VPSHRDVD 99(R15)(R15*4), Y22, K1, Y15              // 62124d2173bcbf63000000
	//TODO: VPSHRDVD 15(DX), Y22, K1, Y15                      // 62724d2173ba0f000000
	//TODO: VPSHRDVD Z3, Z11, K7, Z21                          // 62e2254f73eb
	//TODO: VPSHRDVD Z12, Z11, K7, Z21                         // 62c2254f73ec
	//TODO: VPSHRDVD 15(DX)(BX*1), Z11, K7, Z21                // 62e2254f73ac1a0f000000
	//TODO: VPSHRDVD -7(CX)(DX*2), Z11, K7, Z21                // 62e2254f73ac51f9ffffff
	//TODO: VPSHRDVD Z3, Z25, K7, Z21                          // 62e2354773eb
	//TODO: VPSHRDVD Z12, Z25, K7, Z21                         // 62c2354773ec
	//TODO: VPSHRDVD 15(DX)(BX*1), Z25, K7, Z21                // 62e2354773ac1a0f000000
	//TODO: VPSHRDVD -7(CX)(DX*2), Z25, K7, Z21                // 62e2354773ac51f9ffffff
	//TODO: VPSHRDVD Z3, Z11, K7, Z13                          // 6272254f73eb
	//TODO: VPSHRDVD Z12, Z11, K7, Z13                         // 6252254f73ec
	//TODO: VPSHRDVD 15(DX)(BX*1), Z11, K7, Z13                // 6272254f73ac1a0f000000
	//TODO: VPSHRDVD -7(CX)(DX*2), Z11, K7, Z13                // 6272254f73ac51f9ffffff
	//TODO: VPSHRDVD Z3, Z25, K7, Z13                          // 6272354773eb
	//TODO: VPSHRDVD Z12, Z25, K7, Z13                         // 6252354773ec
	//TODO: VPSHRDVD 15(DX)(BX*1), Z25, K7, Z13                // 6272354773ac1a0f000000
	//TODO: VPSHRDVD -7(CX)(DX*2), Z25, K7, Z13                // 6272354773ac51f9ffffff
	//TODO: VPSHRDVQ X0, X14, K1, X24                          // 62628d0973c0
	//TODO: VPSHRDVQ 99(R15)(R15*8), X14, K1, X24              // 62028d097384ff63000000
	//TODO: VPSHRDVQ 7(AX)(CX*8), X14, K1, X24                 // 62628d097384c807000000
	//TODO: VPSHRDVQ Y9, Y24, K1, Y18                          // 62c2bd2173d1
	//TODO: VPSHRDVQ (CX), Y24, K1, Y18                        // 62e2bd217311
	//TODO: VPSHRDVQ 99(R15), Y24, K1, Y18                     // 62c2bd21739763000000
	//TODO: VPSHRDVQ Z23, Z23, K1, Z27                         // 6222c54173df
	//TODO: VPSHRDVQ Z6, Z23, K1, Z27                          // 6262c54173de
	//TODO: VPSHRDVQ -17(BP), Z23, K1, Z27                     // 6262c541739defffffff
	//TODO: VPSHRDVQ -15(R14)(R15*8), Z23, K1, Z27             // 6202c541739cfef1ffffff
	//TODO: VPSHRDVQ Z23, Z5, K1, Z27                          // 6222d54973df
	//TODO: VPSHRDVQ Z6, Z5, K1, Z27                           // 6262d54973de
	//TODO: VPSHRDVQ -17(BP), Z5, K1, Z27                      // 6262d549739defffffff
	//TODO: VPSHRDVQ -15(R14)(R15*8), Z5, K1, Z27              // 6202d549739cfef1ffffff
	//TODO: VPSHRDVQ Z23, Z23, K1, Z15                         // 6232c54173ff
	//TODO: VPSHRDVQ Z6, Z23, K1, Z15                          // 6272c54173fe
	//TODO: VPSHRDVQ -17(BP), Z23, K1, Z15                     // 6272c54173bdefffffff
	//TODO: VPSHRDVQ -15(R14)(R15*8), Z23, K1, Z15             // 6212c54173bcfef1ffffff
	//TODO: VPSHRDVQ Z23, Z5, K1, Z15                          // 6232d54973ff
	//TODO: VPSHRDVQ Z6, Z5, K1, Z15                           // 6272d54973fe
	//TODO: VPSHRDVQ -17(BP), Z5, K1, Z15                      // 6272d54973bdefffffff
	//TODO: VPSHRDVQ -15(R14)(R15*8), Z5, K1, Z15              // 6212d54973bcfef1ffffff
	//TODO: VPSHRDVW X2, X23, K7, X11                          // 6272c50772da
	//TODO: VPSHRDVW (AX), X23, K7, X11                        // 6272c5077218
	//TODO: VPSHRDVW 7(SI), X23, K7, X11                       // 6272c507729e07000000
	//TODO: VPSHRDVW Y23, Y19, K2, Y3                          // 62b2e52272df
	//TODO: VPSHRDVW 99(R15)(R15*2), Y19, K2, Y3               // 6292e522729c7f63000000
	//TODO: VPSHRDVW -7(DI), Y19, K2, Y3                       // 62f2e522729ff9ffffff
	//TODO: VPSHRDVW Z16, Z21, K4, Z8                          // 6232d54472c0
	//TODO: VPSHRDVW Z13, Z21, K4, Z8                          // 6252d54472c5
	//TODO: VPSHRDVW 17(SP)(BP*2), Z21, K4, Z8                 // 6272d54472846c11000000
	//TODO: VPSHRDVW -7(DI)(R8*4), Z21, K4, Z8                 // 6232d544728487f9ffffff
	//TODO: VPSHRDVW Z16, Z5, K4, Z8                           // 6232d54c72c0
	//TODO: VPSHRDVW Z13, Z5, K4, Z8                           // 6252d54c72c5
	//TODO: VPSHRDVW 17(SP)(BP*2), Z5, K4, Z8                  // 6272d54c72846c11000000
	//TODO: VPSHRDVW -7(DI)(R8*4), Z5, K4, Z8                  // 6232d54c728487f9ffffff
	//TODO: VPSHRDVW Z16, Z21, K4, Z28                         // 6222d54472e0
	//TODO: VPSHRDVW Z13, Z21, K4, Z28                         // 6242d54472e5
	//TODO: VPSHRDVW 17(SP)(BP*2), Z21, K4, Z28                // 6262d54472a46c11000000
	//TODO: VPSHRDVW -7(DI)(R8*4), Z21, K4, Z28                // 6222d54472a487f9ffffff
	//TODO: VPSHRDVW Z16, Z5, K4, Z28                          // 6222d54c72e0
	//TODO: VPSHRDVW Z13, Z5, K4, Z28                          // 6242d54c72e5
	//TODO: VPSHRDVW 17(SP)(BP*2), Z5, K4, Z28                 // 6262d54c72a46c11000000
	//TODO: VPSHRDVW -7(DI)(R8*4), Z5, K4, Z28                 // 6222d54c72a487f9ffffff
	//TODO: VPSHRDW $27, X25, X5, K1, X20                      // 6283d50972e11b
	//TODO: VPSHRDW $27, (BX), X5, K1, X20                     // 62e3d50972231b
	//TODO: VPSHRDW $27, -17(BP)(SI*1), X5, K1, X20            // 62e3d50972a435efffffff1b
	//TODO: VPSHRDW $47, Y21, Y14, K3, Y19                     // 62a38d2b72dd2f
	//TODO: VPSHRDW $47, -7(CX)(DX*1), Y14, K3, Y19            // 62e38d2b729c11f9ffffff2f
	//TODO: VPSHRDW $47, -15(R14)(R15*4), Y14, K3, Y19         // 62838d2b729cbef1ffffff2f
	//TODO: VPSHRDW $82, Z6, Z22, K4, Z12                      // 6273cd4472e652
	//TODO: VPSHRDW $82, Z8, Z22, K4, Z12                      // 6253cd4472e052
	//TODO: VPSHRDW $82, 15(R8), Z22, K4, Z12                  // 6253cd4472a00f00000052
	//TODO: VPSHRDW $82, (BP), Z22, K4, Z12                    // 6273cd4472650052
	//TODO: VPSHRDW $82, Z6, Z11, K4, Z12                      // 6273a54c72e652
	//TODO: VPSHRDW $82, Z8, Z11, K4, Z12                      // 6253a54c72e052
	//TODO: VPSHRDW $82, 15(R8), Z11, K4, Z12                  // 6253a54c72a00f00000052
	//TODO: VPSHRDW $82, (BP), Z11, K4, Z12                    // 6273a54c72650052
	//TODO: VPSHRDW $82, Z6, Z22, K4, Z27                      // 6263cd4472de52
	//TODO: VPSHRDW $82, Z8, Z22, K4, Z27                      // 6243cd4472d852
	//TODO: VPSHRDW $82, 15(R8), Z22, K4, Z27                  // 6243cd4472980f00000052
	//TODO: VPSHRDW $82, (BP), Z22, K4, Z27                    // 6263cd44725d0052
	//TODO: VPSHRDW $82, Z6, Z11, K4, Z27                      // 6263a54c72de52
	//TODO: VPSHRDW $82, Z8, Z11, K4, Z27                      // 6243a54c72d852
	//TODO: VPSHRDW $82, 15(R8), Z11, K4, Z27                  // 6243a54c72980f00000052
	//TODO: VPSHRDW $82, (BP), Z11, K4, Z27                    // 6263a54c725d0052
	RET
