// Code generated by avx512test. DO NOT EDIT.

#include "../../../../../../runtime/textflag.h"

TEXT asmtest_avx512_ifma(SB), NOSPLIT, $0
	//TODO: VPMADD52HUQ X8, X7, K1, X16                        // 62c2c509b5c0
	//TODO: VPMADD52HUQ 17(SP)(BP*2), X7, K1, X16              // 62e2c509b5846c11000000
	//TODO: VPMADD52HUQ -7(DI)(R8*4), X7, K1, X16              // 62a2c509b58487f9ffffff
	//TODO: VPMADD52HUQ Y2, Y28, K7, Y31                       // 62629d27b5fa
	//TODO: VPMADD52HUQ (R8), Y28, K7, Y31                     // 62429d27b538
	//TODO: VPMADD52HUQ 15(DX)(BX*2), Y28, K7, Y31             // 62629d27b5bc5a0f000000
	//TODO: VPMADD52HUQ Z23, Z23, K1, Z27                      // 6222c541b5df
	//TODO: VPMADD52HUQ Z6, Z23, K1, Z27                       // 6262c541b5de
	//TODO: VPMADD52HUQ 17(SP), Z23, K1, Z27                   // 6262c541b59c2411000000
	//TODO: VPMADD52HUQ -17(BP)(SI*4), Z23, K1, Z27            // 6262c541b59cb5efffffff
	//TODO: VPMADD52HUQ Z23, Z5, K1, Z27                       // 6222d549b5df
	//TODO: VPMADD52HUQ Z6, Z5, K1, Z27                        // 6262d549b5de
	//TODO: VPMADD52HUQ 17(SP), Z5, K1, Z27                    // 6262d549b59c2411000000
	//TODO: VPMADD52HUQ -17(BP)(SI*4), Z5, K1, Z27             // 6262d549b59cb5efffffff
	//TODO: VPMADD52HUQ Z23, Z23, K1, Z15                      // 6232c541b5ff
	//TODO: VPMADD52HUQ Z6, Z23, K1, Z15                       // 6272c541b5fe
	//TODO: VPMADD52HUQ 17(SP), Z23, K1, Z15                   // 6272c541b5bc2411000000
	//TODO: VPMADD52HUQ -17(BP)(SI*4), Z23, K1, Z15            // 6272c541b5bcb5efffffff
	//TODO: VPMADD52HUQ Z23, Z5, K1, Z15                       // 6232d549b5ff
	//TODO: VPMADD52HUQ Z6, Z5, K1, Z15                        // 6272d549b5fe
	//TODO: VPMADD52HUQ 17(SP), Z5, K1, Z15                    // 6272d549b5bc2411000000
	//TODO: VPMADD52HUQ -17(BP)(SI*4), Z5, K1, Z15             // 6272d549b5bcb5efffffff
	//TODO: VPMADD52LUQ X15, X0, K1, X1                        // 62d2fd09b4cf
	//TODO: VPMADD52LUQ 15(R8), X0, K1, X1                     // 62d2fd09b4880f000000
	//TODO: VPMADD52LUQ (BP), X0, K1, X1                       // 62f2fd09b44d00
	//TODO: VPMADD52LUQ Y0, Y27, K1, Y24                       // 6262a521b4c0
	//TODO: VPMADD52LUQ 17(SP)(BP*1), Y27, K1, Y24             // 6262a521b4842c11000000
	//TODO: VPMADD52LUQ -7(CX)(DX*8), Y27, K1, Y24             // 6262a521b484d1f9ffffff
	//TODO: VPMADD52LUQ Z16, Z21, K7, Z8                       // 6232d547b4c0
	//TODO: VPMADD52LUQ Z13, Z21, K7, Z8                       // 6252d547b4c5
	//TODO: VPMADD52LUQ 7(AX), Z21, K7, Z8                     // 6272d547b48007000000
	//TODO: VPMADD52LUQ (DI), Z21, K7, Z8                      // 6272d547b407
	//TODO: VPMADD52LUQ Z16, Z5, K7, Z8                        // 6232d54fb4c0
	//TODO: VPMADD52LUQ Z13, Z5, K7, Z8                        // 6252d54fb4c5
	//TODO: VPMADD52LUQ 7(AX), Z5, K7, Z8                      // 6272d54fb48007000000
	//TODO: VPMADD52LUQ (DI), Z5, K7, Z8                       // 6272d54fb407
	//TODO: VPMADD52LUQ Z16, Z21, K7, Z28                      // 6222d547b4e0
	//TODO: VPMADD52LUQ Z13, Z21, K7, Z28                      // 6242d547b4e5
	//TODO: VPMADD52LUQ 7(AX), Z21, K7, Z28                    // 6262d547b4a007000000
	//TODO: VPMADD52LUQ (DI), Z21, K7, Z28                     // 6262d547b427
	//TODO: VPMADD52LUQ Z16, Z5, K7, Z28                       // 6222d54fb4e0
	//TODO: VPMADD52LUQ Z13, Z5, K7, Z28                       // 6242d54fb4e5
	//TODO: VPMADD52LUQ 7(AX), Z5, K7, Z28                     // 6262d54fb4a007000000
	//TODO: VPMADD52LUQ (DI), Z5, K7, Z28                      // 6262d54fb427
	RET
