// Code generated by avx512test. DO NOT EDIT.

#include "../../../../../../runtime/textflag.h"

TEXT asmtest_avx512cd(SB), NOSPLIT, $0
	//TODO: VPBROADCASTMB2Q K1, X11                            // 6272fe082ad9
	//TODO: VPBROADCASTMB2Q K5, X11                            // 6272fe082add
	//TODO: VPBROADCASTMB2Q K3, Y5                             // 62f2fe282aeb
	//TODO: VPBROADCASTMB2Q K1, Y5                             // 62f2fe282ae9
	//TODO: VPBROADCASTMB2Q K5, Z21                            // 62e2fe482aed
	//TODO: VPBROADCASTMB2Q K4, Z21                            // 62e2fe482aec
	//TODO: VPBROADCASTMB2Q K5, Z8                             // 6272fe482ac5
	//TODO: VPBROADCASTMB2Q K4, Z8                             // 6272fe482ac4
	//TODO: VPBROADCASTMW2D K7, X31                            // 62627e083aff
	//TODO: VPBROADCASTMW2D K6, X31                            // 62627e083afe
	//TODO: VPBROADCASTMW2D K4, Y28                            // 62627e283ae4
	//TODO: VPBROADCASTMW2D K6, Y28                            // 62627e283ae6
	//TODO: VPBROADCASTMW2D K0, Z16                            // 62e27e483ac0
	//TODO: VPBROADCASTMW2D K7, Z16                            // 62e27e483ac7
	//TODO: VPBROADCASTMW2D K0, Z9                             // 62727e483ac8
	//TODO: VPBROADCASTMW2D K7, Z9                             // 62727e483acf
	//TODO: VPCONFLICTD X14, K6, X5                            // 62d27d0ec4ee
	//TODO: VPCONFLICTD 15(R8), K6, X5                         // 62d27d0ec4a80f000000
	//TODO: VPCONFLICTD (BP), K6, X5                           // 62f27d0ec46d00
	//TODO: VPCONFLICTD Y1, K3, Y21                            // 62e27d2bc4e9
	//TODO: VPCONFLICTD -7(CX), K3, Y21                        // 62e27d2bc4a9f9ffffff
	//TODO: VPCONFLICTD 15(DX)(BX*4), K3, Y21                  // 62e27d2bc4ac9a0f000000
	//TODO: VPCONFLICTD Z11, K7, Z21                           // 62c27d4fc4eb
	//TODO: VPCONFLICTD Z25, K7, Z21                           // 62827d4fc4e9
	//TODO: VPCONFLICTD -15(R14)(R15*1), K7, Z21               // 62827d4fc4ac3ef1ffffff
	//TODO: VPCONFLICTD -15(BX), K7, Z21                       // 62e27d4fc4abf1ffffff
	//TODO: VPCONFLICTD Z11, K7, Z13                           // 62527d4fc4eb
	//TODO: VPCONFLICTD Z25, K7, Z13                           // 62127d4fc4e9
	//TODO: VPCONFLICTD -15(R14)(R15*1), K7, Z13               // 62127d4fc4ac3ef1ffffff
	//TODO: VPCONFLICTD -15(BX), K7, Z13                       // 62727d4fc4abf1ffffff
	//TODO: VPCONFLICTQ X17, K4, X0                            // 62b2fd0cc4c1
	//TODO: VPCONFLICTQ 15(R8)(R14*8), K4, X0                  // 6292fd0cc484f00f000000
	//TODO: VPCONFLICTQ -15(R14)(R15*2), K4, X0                // 6292fd0cc4847ef1ffffff
	//TODO: VPCONFLICTQ Y30, K4, Y26                           // 6202fd2cc4d6
	//TODO: VPCONFLICTQ 99(R15)(R15*8), K4, Y26                // 6202fd2cc494ff63000000
	//TODO: VPCONFLICTQ 7(AX)(CX*8), K4, Y26                   // 6262fd2cc494c807000000
	//TODO: VPCONFLICTQ Z27, K7, Z3                            // 6292fd4fc4db
	//TODO: VPCONFLICTQ Z15, K7, Z3                            // 62d2fd4fc4df
	//TODO: VPCONFLICTQ 7(AX)(CX*4), K7, Z3                    // 62f2fd4fc49c8807000000
	//TODO: VPCONFLICTQ 7(AX)(CX*1), K7, Z3                    // 62f2fd4fc49c0807000000
	//TODO: VPCONFLICTQ Z27, K7, Z12                           // 6212fd4fc4e3
	//TODO: VPCONFLICTQ Z15, K7, Z12                           // 6252fd4fc4e7
	//TODO: VPCONFLICTQ 7(AX)(CX*4), K7, Z12                   // 6272fd4fc4a48807000000
	//TODO: VPCONFLICTQ 7(AX)(CX*1), K7, Z12                   // 6272fd4fc4a40807000000
	//TODO: VPLZCNTD X19, K3, X26                              // 62227d0b44d3
	//TODO: VPLZCNTD 15(DX)(BX*1), K3, X26                     // 62627d0b44941a0f000000
	//TODO: VPLZCNTD -7(CX)(DX*2), K3, X26                     // 62627d0b449451f9ffffff
	//TODO: VPLZCNTD Y0, K3, Y5                                // 62f27d2b44e8
	//TODO: VPLZCNTD (BX), K3, Y5                              // 62f27d2b442b
	//TODO: VPLZCNTD -17(BP)(SI*1), K3, Y5                     // 62f27d2b44ac35efffffff
	//TODO: VPLZCNTD Z21, K3, Z3                               // 62b27d4b44dd
	//TODO: VPLZCNTD Z13, K3, Z3                               // 62d27d4b44dd
	//TODO: VPLZCNTD 17(SP)(BP*8), K3, Z3                      // 62f27d4b449cec11000000
	//TODO: VPLZCNTD 17(SP)(BP*4), K3, Z3                      // 62f27d4b449cac11000000
	//TODO: VPLZCNTD Z21, K3, Z0                               // 62b27d4b44c5
	//TODO: VPLZCNTD Z13, K3, Z0                               // 62d27d4b44c5
	//TODO: VPLZCNTD 17(SP)(BP*8), K3, Z0                      // 62f27d4b4484ec11000000
	//TODO: VPLZCNTD 17(SP)(BP*4), K3, Z0                      // 62f27d4b4484ac11000000
	//TODO: VPLZCNTQ X31, K2, X0                               // 6292fd0a44c7
	//TODO: VPLZCNTQ -17(BP), K2, X0                           // 62f2fd0a4485efffffff
	//TODO: VPLZCNTQ -15(R14)(R15*8), K2, X0                   // 6292fd0a4484fef1ffffff
	//TODO: VPLZCNTQ Y19, K1, Y5                               // 62b2fd2944eb
	//TODO: VPLZCNTQ 15(R8)(R14*4), K1, Y5                     // 6292fd2944acb00f000000
	//TODO: VPLZCNTQ -7(CX)(DX*4), K1, Y5                      // 62f2fd2944ac91f9ffffff
	//TODO: VPLZCNTQ Z3, K2, Z11                               // 6272fd4a44db
	//TODO: VPLZCNTQ Z12, K2, Z11                              // 6252fd4a44dc
	//TODO: VPLZCNTQ 7(SI)(DI*4), K2, Z11                      // 6272fd4a449cbe07000000
	//TODO: VPLZCNTQ -7(DI)(R8*2), K2, Z11                     // 6232fd4a449c47f9ffffff
	//TODO: VPLZCNTQ Z3, K2, Z25                               // 6262fd4a44cb
	//TODO: VPLZCNTQ Z12, K2, Z25                              // 6242fd4a44cc
	//TODO: VPLZCNTQ 7(SI)(DI*4), K2, Z25                      // 6262fd4a448cbe07000000
	//TODO: VPLZCNTQ -7(DI)(R8*2), K2, Z25                     // 6222fd4a448c47f9ffffff
	RET
