// Code generated by avx512test. DO NOT EDIT.

#include "../../../../../../runtime/textflag.h"

TEXT asmtest_gfni_avx512f(SB), NOSPLIT, $0
	//TODO: VGF2P8AFFINEINVQB $64, X6, X13, K3, X30            // 6263950bcff640
	//TODO: VGF2P8AFFINEINVQB $64, -17(BP), X13, K3, X30       // 6263950bcfb5efffffff40
	//TODO: VGF2P8AFFINEINVQB $64, -15(R14)(R15*8), X13, K3, X30 // 6203950bcfb4fef1ffffff40
	//TODO: VGF2P8AFFINEINVQB $27, Y2, Y7, K3, Y13             // 6273c52bcfea1b
	//TODO: VGF2P8AFFINEINVQB $27, (BX), Y7, K3, Y13           // 6273c52bcf2b1b
	//TODO: VGF2P8AFFINEINVQB $27, -17(BP)(SI*1), Y7, K3, Y13  // 6273c52bcfac35efffffff1b
	//TODO: VGF2P8AFFINEINVQB $47, Z3, Z14, K2, Z28            // 62638d4acfe32f
	//TODO: VGF2P8AFFINEINVQB $47, Z12, Z14, K2, Z28           // 62438d4acfe42f
	//TODO: VGF2P8AFFINEINVQB $47, 99(R15)(R15*1), Z14, K2, Z28 // 62038d4acfa43f630000002f
	//TODO: VGF2P8AFFINEINVQB $47, (DX), Z14, K2, Z28          // 62638d4acf222f
	//TODO: VGF2P8AFFINEINVQB $47, Z3, Z28, K2, Z28            // 62639d42cfe32f
	//TODO: VGF2P8AFFINEINVQB $47, Z12, Z28, K2, Z28           // 62439d42cfe42f
	//TODO: VGF2P8AFFINEINVQB $47, 99(R15)(R15*1), Z28, K2, Z28 // 62039d42cfa43f630000002f
	//TODO: VGF2P8AFFINEINVQB $47, (DX), Z28, K2, Z28          // 62639d42cf222f
	//TODO: VGF2P8AFFINEINVQB $47, Z3, Z14, K2, Z13            // 62738d4acfeb2f
	//TODO: VGF2P8AFFINEINVQB $47, Z12, Z14, K2, Z13           // 62538d4acfec2f
	//TODO: VGF2P8AFFINEINVQB $47, 99(R15)(R15*1), Z14, K2, Z13 // 62138d4acfac3f630000002f
	//TODO: VGF2P8AFFINEINVQB $47, (DX), Z14, K2, Z13          // 62738d4acf2a2f
	//TODO: VGF2P8AFFINEINVQB $47, Z3, Z28, K2, Z13            // 62739d42cfeb2f
	//TODO: VGF2P8AFFINEINVQB $47, Z12, Z28, K2, Z13           // 62539d42cfec2f
	//TODO: VGF2P8AFFINEINVQB $47, 99(R15)(R15*1), Z28, K2, Z13 // 62139d42cfac3f630000002f
	//TODO: VGF2P8AFFINEINVQB $47, (DX), Z28, K2, Z13          // 62739d42cf2a2f
	//TODO: VGF2P8AFFINEQB $82, X30, X23, K1, X12              // 6213c501cee652
	//TODO: VGF2P8AFFINEQB $82, 17(SP)(BP*2), X23, K1, X12     // 6273c501cea46c1100000052
	//TODO: VGF2P8AFFINEQB $82, -7(DI)(R8*4), X23, K1, X12     // 6233c501cea487f9ffffff52
	//TODO: VGF2P8AFFINEQB $126, Y9, Y12, K2, Y21              // 62c39d2acee97e
	//TODO: VGF2P8AFFINEQB $126, 15(R8)(R14*4), Y12, K2, Y21   // 62839d2aceacb00f0000007e
	//TODO: VGF2P8AFFINEQB $126, -7(CX)(DX*4), Y12, K2, Y21    // 62e39d2aceac91f9ffffff7e
	//TODO: VGF2P8AFFINEQB $94, Z5, Z19, K1, Z15               // 6273e541cefd5e
	//TODO: VGF2P8AFFINEQB $94, Z1, Z19, K1, Z15               // 6273e541cef95e
	//TODO: VGF2P8AFFINEQB $94, -17(BP)(SI*8), Z19, K1, Z15    // 6273e541cebcf5efffffff5e
	//TODO: VGF2P8AFFINEQB $94, (R15), Z19, K1, Z15            // 6253e541ce3f5e
	//TODO: VGF2P8AFFINEQB $94, Z5, Z15, K1, Z15               // 62738549cefd5e
	//TODO: VGF2P8AFFINEQB $94, Z1, Z15, K1, Z15               // 62738549cef95e
	//TODO: VGF2P8AFFINEQB $94, -17(BP)(SI*8), Z15, K1, Z15    // 62738549cebcf5efffffff5e
	//TODO: VGF2P8AFFINEQB $94, (R15), Z15, K1, Z15            // 62538549ce3f5e
	//TODO: VGF2P8AFFINEQB $94, Z5, Z19, K1, Z30               // 6263e541cef55e
	//TODO: VGF2P8AFFINEQB $94, Z1, Z19, K1, Z30               // 6263e541cef15e
	//TODO: VGF2P8AFFINEQB $94, -17(BP)(SI*8), Z19, K1, Z30    // 6263e541ceb4f5efffffff5e
	//TODO: VGF2P8AFFINEQB $94, (R15), Z19, K1, Z30            // 6243e541ce375e
	//TODO: VGF2P8AFFINEQB $94, Z5, Z15, K1, Z30               // 62638549cef55e
	//TODO: VGF2P8AFFINEQB $94, Z1, Z15, K1, Z30               // 62638549cef15e
	//TODO: VGF2P8AFFINEQB $94, -17(BP)(SI*8), Z15, K1, Z30    // 62638549ceb4f5efffffff5e
	//TODO: VGF2P8AFFINEQB $94, (R15), Z15, K1, Z30            // 62438549ce375e
	//TODO: VGF2P8MULB X2, X20, K7, X8                         // 62725d07cfc2
	//TODO: VGF2P8MULB 15(R8), X20, K7, X8                     // 62525d07cf800f000000
	//TODO: VGF2P8MULB (BP), X20, K7, X8                       // 62725d07cf4500
	//TODO: VGF2P8MULB Y3, Y9, K1, Y1                          // 62f23529cfcb
	//TODO: VGF2P8MULB (R8), Y9, K1, Y1                        // 62d23529cf08
	//TODO: VGF2P8MULB 15(DX)(BX*2), Y9, K1, Y1                // 62f23529cf8c5a0f000000
	//TODO: VGF2P8MULB Z21, Z14, K1, Z3                        // 62b20d49cfdd
	//TODO: VGF2P8MULB Z8, Z14, K1, Z3                         // 62d20d49cfd8
	//TODO: VGF2P8MULB 7(SI)(DI*8), Z14, K1, Z3                // 62f20d49cf9cfe07000000
	//TODO: VGF2P8MULB -15(R14), Z14, K1, Z3                   // 62d20d49cf9ef1ffffff
	//TODO: VGF2P8MULB Z21, Z15, K1, Z3                        // 62b20549cfdd
	//TODO: VGF2P8MULB Z8, Z15, K1, Z3                         // 62d20549cfd8
	//TODO: VGF2P8MULB 7(SI)(DI*8), Z15, K1, Z3                // 62f20549cf9cfe07000000
	//TODO: VGF2P8MULB -15(R14), Z15, K1, Z3                   // 62d20549cf9ef1ffffff
	//TODO: VGF2P8MULB Z21, Z14, K1, Z5                        // 62b20d49cfed
	//TODO: VGF2P8MULB Z8, Z14, K1, Z5                         // 62d20d49cfe8
	//TODO: VGF2P8MULB 7(SI)(DI*8), Z14, K1, Z5                // 62f20d49cfacfe07000000
	//TODO: VGF2P8MULB -15(R14), Z14, K1, Z5                   // 62d20d49cfaef1ffffff
	//TODO: VGF2P8MULB Z21, Z15, K1, Z5                        // 62b20549cfed
	//TODO: VGF2P8MULB Z8, Z15, K1, Z5                         // 62d20549cfe8
	//TODO: VGF2P8MULB 7(SI)(DI*8), Z15, K1, Z5                // 62f20549cfacfe07000000
	//TODO: VGF2P8MULB -15(R14), Z15, K1, Z5                   // 62d20549cfaef1ffffff
	RET
