// Code generated by "stringer -type=InstParam"; DO NOT EDIT.

package x86encode

import "strconv"

const _InstParam_name = "ParamBadParamRexW0ParamRexW1ParamVexL128ParamVexL256ParamVexL512ParamEOSZ8ParamEOSZ16ParamEOSZ32ParamEOSZ64"

var _InstParam_index = [...]uint8{0, 8, 18, 28, 40, 52, 64, 74, 85, 96, 107}

func (i InstParam) String() string {
	if i < 0 || i >= InstParam(len(_InstParam_index)-1) {
		return "InstParam(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _InstParam_name[_InstParam_index[i]:_InstParam_index[i+1]]
}
