// +build generate

package main

// #cgo LDFLAGS: -lxed
// #include <xed/xed-interface.h>
import "C"

import (
	"bytes"
	"fmt"
	"go/format"
)

func main() {
	var buf bytes.Buffer
	clauses := []func(*bytes.Buffer){
		writePackageHeader,
		writeRegisterMap,
		writeIclassMap,
	}
	for i := range clauses {
		clauses[i](&buf)
		buf.WriteByte('\n')
	}

	code, err := format.Source(buf.Bytes())
	if err != nil {
		panic(err)
	}
	fmt.Print(string(code))
}

func writeLines(buf *bytes.Buffer, lines []string) {
	for _, line := range lines {
		buf.WriteString(line)
		buf.WriteByte('\n')
	}
}

func writePackageHeader(buf *bytes.Buffer) {
	writeLines(buf, []string{
		"// Code generated by xed_tables.go. DO NOT EDIT.",
		"",
		"package x86encode",
	})
}

func writeRegisterMap(buf *bytes.Buffer) {
	var lines []string
	regFirst := int(C.XED_REG_INVALID)
	regLast := int(C.XED_REG_LAST)
	for i := regFirst; i < regLast; i++ {
		id := C.xed_reg_enum_t(i)
		name := C.GoString(C.xed_reg_enum_t2str(id))
		lines = append(lines, fmt.Sprintf("\t%q: %d,", name, i))
	}

	buf.WriteString("var registerByName = map[string]int{\n")
	writeLines(buf, lines)
	buf.WriteString("}\n")
}

func writeIclassMap(buf *bytes.Buffer) {
	var lines []string

	iclassFirst := int(C.XED_ICLASS_INVALID)
	iclassLast := int(C.XED_ICLASS_LAST)
	for i := iclassFirst; i < iclassLast; i++ {
		id := C.xed_iclass_enum_t(i)
		name := C.GoString(C.xed_iclass_enum_t2str(id))
		lines = append(lines, fmt.Sprintf("\t%q: %d,", name, i))
	}

	buf.WriteString("var iclassByOpcode = map[string]int{\n")
	writeLines(buf, lines)
	buf.WriteString("}\n")
}
